'use client';
import { useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';

type Master={ps:number;oldPs:number|null;anomaly:number;mapping:number;grandTotal:number;blo:string;supervisor:string;officer:string;hearingCentre:string;address:string;locality:string;pollingArea:string;voters:number};
type Eci=Record<string,unknown>&{ps:number};
type MapRow={centre:string;officer:string;contact:string};
type Cat={anGen:number;nmGen:number;anPend:number;nmPend:number;anDel:number;nmDel:number;anPdel:number;nmPdel:number;gen:number;pgen:number;del:number;pdel:number};
type Joined=Eci&{m:Master;cat:Cat;map:MapRow|null};
type SortDir='asc'|'desc'; type SortState={key:string;dir:SortDir};
type OfficerRow={officer:string;centre:string;contact:string;ps:number;totalNoMap:number;nmGen:number;nmPend:number;nmDel:number;nmPdel:number;hearings:number;hearingLapsed:number;rescheduleLapsed:number;deoPending:number;deo5:number};
type HistoryItem={time:string;kind:string;rows:number;generated:number;pending:number;delivered:number;pendingDelivery:number};

const MAP:Array<[string,number,number,string,string]>=[
['GCSSS, SEC-3 DWARKA(P)',1,50,'SH. PARVEEN KUMAR','9953601073'],['GCSSS, SEC-3 DWARKA(P)',55,60,'SH. PARVEEN KUMAR','9953601073'],['GCSSS, SEC-3 DWARKA(P)',78,79,'SH. PARVEEN KUMAR','9953601073'],['GCSSS, SEC-3 DWARKA(P)',91,96,'SH. PARVEEN KUMAR','9953601073'],
['GCSSS, SEC-3 DWARKA(S)',51,54,'SMT. SHASHI BALA','9953312984'],['GCSSS, SEC-3 DWARKA(S)',61,77,'SMT. SHASHI BALA','9953312984'],['GCSSS, SEC-3 DWARKA(S)',80,90,'SMT. SHASHI BALA','9953312984'],['GCSSS, SEC-3 DWARKA(S)',97,109,'SMT. SHASHI BALA','9953312984'],['GCSSS, SEC-3 DWARKA(S)',135,145,'SMT. SHASHI BALA','9953312984'],
['GCSSC SEC-22 DWARKA(R)',110,134,'SH. RAKESH KUMAR','7011971522'],['GCSSC SEC-22 DWARKA(R)',331,341,'SH. RAKESH KUMAR','7011971522'],['GCSSC SEC-22 DWARKA(R)',343,344,'SH. RAKESH KUMAR','7011971522'],['GCSSC SEC-22 DWARKA(R)',347,349,'SH. RAKESH KUMAR','7011971522'],
['VREC MATIALA',146,234,'SMT. PARUL GUPTA','9667881989'],['VREC MATIALA',276,288,'SMT. PARUL GUPTA','9667881989'],['MCD BOYS PRIMARY SCHOOL, QUTUB VIHAR',235,275,'SH. SUBHASHISH','9868252144'],['MCD BOYS PRIMARY SCHOOL, QUTUB VIHAR',289,330,'SH. SUBHASHISH','9868252144'],
['GCSSS SEC 22 DWARKA(V)',342,342,'SH. VIRENDER','9868252144'],['GCSSS SEC 22 DWARKA(V)',345,346,'SH. VIRENDER','9868252144'],['GCSSS SEC 22 DWARKA(V)',350,374,'SH. VIRENDER','9868252144'],['GCSSS GHUMANHERA',375,430,'SH. VIRENDER','9868252144']];
const centres=[...new Set(MAP.map(x=>x[0]))];
const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:0};
const s=(v:unknown)=>String(v??'').trim(); const key=(v:unknown)=>s(v).toLowerCase(); const fmt=(v:number)=>v.toLocaleString('en-IN');
const centre=(ps:number):MapRow|null=>{const x=MAP.find(m=>ps>=m[1]&&ps<=m[2]);return x?{centre:x[0],officer:x[3],contact:x[4]}:null};
const field=(r:Eci,...names:string[])=>{for(const name of names){if(name in r&&s(r[name])!=='')return r[name]}return ''};
const fieldNum=(r:Eci,...names:string[])=>n(field(r,...names));
function parseEci(rows:unknown[][]):Eci[]{if(!rows.length)return[];const heads=rows[0].map(s),ix=(x:string)=>heads.indexOf(x),p=ix('POLLING STATION');if(p<0)throw Error('ECI sheet is missing the POLLING STATION column.');return rows.slice(1).filter(r=>r.some(v=>s(v)!=='')).map(r=>{const o:Record<string,unknown>={};heads.forEach((h,i)=>{if(h)o[h]=r[i]});o.ps=Math.trunc(n(r[p]));return o as Eci}).filter(r=>r.ps>=1&&r.ps<=430)}
function parseMaster(rows:unknown[][]):Master[]{if(rows.length<3)return[];const heads=rows[1].map(s),ix=(x:string)=>heads.indexOf(x);const req=['New P.S. No.','Old P.S. No.','Total Anamoly/Discripancy','Total No Mapping','Grand Total','All BLO Name','Supervisor Name','Officer Name (NEW)','Hearing Centre','Address of P.S.','LOCALITY','POLLING AREA','Total Voters'];const miss=req.filter(x=>ix(x)<0);if(miss.length)throw Error(`Master sheet is missing: ${miss.join(', ')}`);return rows.slice(2).filter(r=>r[ix('New P.S. No.')]!==''&&r[ix('New P.S. No.')]!=null).map(r=>({ps:Math.trunc(n(r[ix('New P.S. No.')])),oldPs:r[ix('Old P.S. No.')]===''?null:n(r[ix('Old P.S. No.')]),anomaly:n(r[ix('Total Anamoly/Discripancy')]),mapping:n(r[ix('Total No Mapping')]),grandTotal:n(r[ix('Grand Total')]),blo:s(r[ix('All BLO Name')]),supervisor:s(r[ix('Supervisor Name')]),officer:s(r[ix('Officer Name (NEW)')]),hearingCentre:s(r[ix('Hearing Centre')]),address:s(r[ix('Address of P.S.')]),locality:s(r[ix('LOCALITY')]),pollingArea:s(r[ix('POLLING AREA')]),voters:n(r[ix('Total Voters')])}))}
function category(e:Eci,m:Master):Cat{const gen=Math.max(n(e['Notice Generated']),0),pgen=Math.max(n(e['Pending for Notice Generation']),0),del=Math.max(n(e['Notice Delivered']),0),pdel=Math.max(n(e['Notice Pending Delivery']),0);const nmGen=Math.min(gen,Math.max(m.mapping,0)),anGen=Math.min(Math.max(gen-nmGen,0),Math.max(m.anomaly,0)),nmPend=Math.min(pgen,Math.max(m.mapping-nmGen,0)),anPend=Math.min(Math.max(pgen-nmPend,0),Math.max(m.anomaly-anGen,0)),nmDel=Math.min(del,nmGen),anDel=Math.min(Math.max(del-nmDel,0),anGen),nmPdel=Math.min(pdel,Math.max(nmGen-nmDel,0)),anPdel=Math.min(Math.max(pdel-nmPdel,0),Math.max(anGen-anDel,0));return{anGen,nmGen,anPend,nmPend,anDel,nmDel,anPdel,nmPdel,gen,pgen,del,pdel}}
function status(r:Joined){if(fieldNum(r,'DEO-Status Pending GT 5 Days')>0||fieldNum(r,'Hearing Date Lapsed')>0||fieldNum(r,'Reschedule Date Lapsed')>0)return'CRITICAL';if(fieldNum(r,'Pending for Notice Generation')>0||fieldNum(r,'Notice Pending Delivery')>0||fieldNum(r,'DEO-Status Total Pending')>0)return'PENDING';return'CLEAR'}

export default function Dashboard(){
const[master,setMaster]=useState<Master[]>([]),[eci,setEci]=useState<Eci[]>([]),[tab,setTab]=useState('Overview'),[q,setQ]=useState(''),[centreFilter,setCentreFilter]=useState('All'),[statusFilter,setStatusFilter]=useState('All'),[updated,setUpdated]=useState(''),[error,setError]=useState(''),[selected,setSelected]=useState<Joined|null>(null),[history,setHistory]=useState<HistoryItem[]>([]),[autoRefresh,setAutoRefresh]=useState(false);
const[psSort,setPsSort]=useState<SortState>({key:'ps',dir:'asc'}),[centreSort,setCentreSort]=useState<SortState>({key:'centre',dir:'asc'}),[officerSort,setOfficerSort]=useState<SortState>({key:'officer',dir:'asc'});
useEffect(()=>{try{const m=localStorage.getItem('eci-master'),e=localStorage.getItem('eci-current'),t=localStorage.getItem('eci-updated'),h=localStorage.getItem('eci-history');if(m)setMaster(JSON.parse(m));if(e)setEci(JSON.parse(e));if(t)setUpdated(t);if(h)setHistory(JSON.parse(h))}catch{setError('Saved browser data could not be read.')}},[]);
useEffect(()=>{if(!autoRefresh)return;const id=window.setInterval(()=>{try{const e=localStorage.getItem('eci-current'),t=localStorage.getItem('eci-updated');if(e)setEci(JSON.parse(e));if(t)setUpdated(t)}catch{}},30000);return()=>window.clearInterval(id)},[autoRefresh]);
const upload=async(file:File,type:'eci'|'master')=>{setError('');try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),ws=type==='eci'?(wb.Sheets['sirNoticeGenerate']||wb.Sheets[wb.SheetNames[0]]):(wb.Sheets['Rough Data']||wb.Sheets[wb.SheetNames[0]]);if(!ws)throw Error('Required worksheet was not found.');const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''}) as unknown[][];if(type==='eci'){const p=parseEci(rows),u=new Set(p.map(x=>x.ps));if(p.length!==430||u.size!==430)throw Error(`ECI file has ${p.length} unique valid PS rows; expected 430.`);setEci(p);const now=new Date().toLocaleString('en-IN',{hour12:false});setUpdated(now);localStorage.setItem('eci-current',JSON.stringify(p));localStorage.setItem('eci-updated',now);const item:HistoryItem={time:now,kind:'ECI Upload',rows:p.length,generated:p.reduce((a,r)=>a+n(r['Notice Generated']),0),pending:p.reduce((a,r)=>a+n(r['Pending for Notice Generation']),0),delivered:p.reduce((a,r)=>a+n(r['Notice Delivered']),0),pendingDelivery:p.reduce((a,r)=>a+n(r['Notice Pending Delivery']),0)};const next=[item,...history].slice(0,20);setHistory(next);localStorage.setItem('eci-history',JSON.stringify(next))}else{const p=parseMaster(rows),u=new Set(p.map(x=>x.ps));if(p.length!==430||u.size!==430)throw Error(`Master file has ${p.length} unique valid PS rows; expected 430.`);setMaster(p);localStorage.setItem('eci-master',JSON.stringify(p))}}catch(e){setError(e instanceof Error?e.message:'Could not read workbook.')}};
const joined=useMemo<Joined[]>(()=>{const mm=new Map(master.map(m=>[m.ps,m]));return eci.map(e=>{const m=mm.get(e.ps)||{ps:e.ps,oldPs:null,anomaly:0,mapping:0,grandTotal:0,blo:'',supervisor:'',officer:'',hearingCentre:'',address:'',locality:'',pollingArea:'',voters:0};return{...e,m,cat:category(e,m),map:centre(e.ps)}})},[eci,master]);
const cats=(k:keyof Cat)=>joined.reduce((a,r)=>a+n(r.cat[k]),0); const sum=(k:string)=>joined.reduce((a,r)=>a+n(r[k]),0); const totalNoMapping=cats('nmGen')+cats('nmPend');
const filtered=useMemo(()=>joined.filter(r=>(centreFilter==='All'||r.map?.centre===centreFilter)&&(statusFilter==='All'||status(r)===statusFilter)&&(q===''||String(r.ps).includes(q)||key(r.m.blo).includes(key(q))||key(r.m.locality).includes(key(q))||key(r.m.pollingArea).includes(key(q))||key(r.map?.officer).includes(key(q))||key(r.map?.centre).includes(key(q)))),[joined,centreFilter,statusFilter,q]);
const compare=(a:unknown,b:unknown)=>{const an=typeof a==='number'?a:Number(a),bn=typeof b==='number'?b:Number(b);return Number.isFinite(an)&&Number.isFinite(bn)?an-bn:s(a).localeCompare(s(b),undefined,{numeric:true,sensitivity:'base'})};
const valJoined=(r:Joined,k:string):unknown=>({ps:r.ps,oldPs:r.m.oldPs??-1,blo:r.m.blo,officer:r.map?.officer||r.m.officer,centre:r.map?.centre||r.m.hearingCentre,anGen:r.cat.anGen,nmGen:r.cat.nmGen,anPend:r.cat.anPend,nmPend:r.cat.nmPend,anDel:r.cat.anDel,nmDel:r.cat.nmDel,anPdel:r.cat.anPdel,nmPdel:r.cat.nmPdel,hearings:fieldNum(r,'Hearings Held'),deo5:fieldNum(r,'DEO-Status Pending GT 5 Days'),status:status(r)}[k]);
const sortJoined=(rows:Joined[],state=psSort)=>[...rows].sort((a,b)=>(state.dir==='asc'?1:-1)*compare(valJoined(a,state.key),valJoined(b,state.key)));
const toggle=(setter:any,state:SortState,k:string)=>setter(state.key===k?{key:k,dir:state.dir==='asc'?'desc':'asc'}:{key:k,dir:'asc'}); const arrow=(state:SortState,k:string)=>state.key===k?(state.dir==='asc'?' ↑':' ↓'):' ↕';
const th=(label:string,k:string,state:SortState,setter:any,rs=2)=><th rowSpan={rs} className="sortable" onClick={()=>toggle(setter,state,k)}>{label}{arrow(state,k)}</th>;
const officerRows=useMemo<OfficerRow[]>(()=>centres.map(c=>{const rs=joined.filter(r=>r.map?.centre===c);if(!rs.length)return null;return{officer:rs[0].map?.officer||'',centre:c,contact:rs[0].map?.contact||'',ps:rs.length,totalNoMap:rs.reduce((a,r)=>a+r.cat.nmGen+r.cat.nmPend,0),nmGen:rs.reduce((a,r)=>a+r.cat.nmGen,0),nmPend:rs.reduce((a,r)=>a+r.cat.nmPend,0),nmDel:rs.reduce((a,r)=>a+r.cat.nmDel,0),nmPdel:rs.reduce((a,r)=>a+r.cat.nmPdel,0),hearings:rs.reduce((a,r)=>a+fieldNum(r,'Hearings Held'),0),hearingLapsed:rs.reduce((a,r)=>a+fieldNum(r,'Hearing Date Lapsed'),0),rescheduleLapsed:rs.reduce((a,r)=>a+fieldNum(r,'Reschedule Date Lapsed'),0),deoPending:rs.reduce((a,r)=>a+fieldNum(r,'DEO-Status Total Pending'),0),deo5:rs.reduce((a,r)=>a+fieldNum(r,'DEO-Status Pending GT 5 Days'),0)}}).filter(Boolean) as OfficerRow[],[joined]);
const sortedOfficers=useMemo(()=>[...officerRows].sort((a,b)=>(officerSort.dir==='asc'?1:-1)*compare((a as any)[officerSort.key],(b as any)[officerSort.key])),[officerRows,officerSort]);
const officerTotals=useMemo(()=>{const m=new Map<string,{officer:string;contact:string;locations:number;ps:number;total:number;gen:number;pend:number;del:number;pdel:number}>();for(const r of officerRows){const x=m.get(r.officer)||{officer:r.officer,contact:r.contact,locations:0,ps:0,total:0,gen:0,pend:0,del:0,pdel:0};x.locations++;x.ps+=r.ps;x.total+=r.totalNoMap;x.gen+=r.nmGen;x.pend+=r.nmPend;x.del+=r.nmDel;x.pdel+=r.nmPdel;m.set(r.officer,x)}return[...m.values()].sort((a,b)=>b.total-a.total)},[officerRows]);
const centreRows=useMemo(()=>centres.map(c=>{const rs=joined.filter(r=>r.map?.centre===c);return{centre:c,officer:rs[0]?.map?.officer||'',contact:rs[0]?.map?.contact||'',ps:rs.length,total:rs.reduce((a,r)=>a+r.cat.nmGen+r.cat.nmPend,0),gen:rs.reduce((a,r)=>a+r.cat.nmGen,0),pend:rs.reduce((a,r)=>a+r.cat.nmPend,0),del:rs.reduce((a,r)=>a+r.cat.nmDel,0),pdel:rs.reduce((a,r)=>a+r.cat.nmPdel,0),deo5:rs.reduce((a,r)=>a+fieldNum(r,'DEO-Status Pending GT 5 Days'),0)}}),[joined]);
const sortedCentres=useMemo(()=>[...centreRows].sort((a,b)=>(centreSort.dir==='asc'?1:-1)*compare((a as any)[centreSort.key],(b as any)[centreSort.key])),[centreRows,centreSort]);
const hearings=useMemo(()=>joined.filter(r=>field(r,'Hearing Date','Hearing date','HEARING DATE')||field(r,'Reschedule Date','Reschedule date','RESCHEDULE DATE')).map(r=>({r,date:s(field(r,'Hearing Date','Hearing date','HEARING DATE')),reschedule:s(field(r,'Reschedule Date','Reschedule date','RESCHEDULE DATE')),held:fieldNum(r,'Hearings Held'),lapsed:fieldNum(r,'Hearing Date Lapsed'),resLapsed:fieldNum(r,'Reschedule Date Lapsed')})),[joined]);
const deoRows=useMemo(()=>joined.filter(r=>fieldNum(r,'DEO-Status Total Pending')>0||fieldNum(r,'DEO-Status Pending GT 5 Days')>0),[joined]);
const validation=[['ECI PS count',eci.length,430,eci.length===430],['Master PS count',master.length,430,master.length===430],['Generated split',cats('anGen')+cats('nmGen'),sum('Notice Generated'),cats('anGen')+cats('nmGen')===sum('Notice Generated')],['Pending generation split',cats('anPend')+cats('nmPend'),sum('Pending for Notice Generation'),cats('anPend')+cats('nmPend')===sum('Pending for Notice Generation')],['Delivered split',cats('anDel')+cats('nmDel'),sum('Notice Delivered'),cats('anDel')+cats('nmDel')===sum('Notice Delivered')],['Pending delivery split',cats('anPdel')+cats('nmPdel'),sum('Notice Pending Delivery'),cats('anPdel')+cats('nmPdel')===sum('Notice Pending Delivery')]] as Array<[string,number,number,boolean]>;
const exportRows=(rows:Joined[],name:string)=>{const header=['PS','Old PS','BLO','Officer','Hearing Location','Contact','Total No Mapping','Generated No Mapping','Pending Generation No Mapping','Delivered No Mapping','Pending Delivery No Mapping','Hearings Held','Hearing Lapsed','Reschedule Lapsed','DEO Pending','DEO >5','Status','Locality','Polling Area','Address'];const lines=[header,...rows.map(r=>[r.ps,r.m.oldPs??'',r.m.blo,r.map?.officer||r.m.officer,r.map?.centre||r.m.hearingCentre,r.map?.contact||'',r.cat.nmGen+r.cat.nmPend,r.cat.nmGen,r.cat.nmPend,r.cat.nmDel,r.cat.nmPdel,fieldNum(r,'Hearings Held'),fieldNum(r,'Hearing Date Lapsed'),fieldNum(r,'Reschedule Date Lapsed'),fieldNum(r,'DEO-Status Total Pending'),fieldNum(r,'DEO-Status Pending GT 5 Days'),status(r),r.m.locality,r.m.pollingArea,r.m.address])].map(a=>a.map(v=>`"${s(v).replaceAll('"','""')}"`).join(','));const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)};
const exportOfficer=()=>{const header=['Officer','Hearing Location','Contact','PS','Total No Mapping','Generated','Pending Generation','Delivered','Pending Delivery','Hearings','Hearing Lapsed','Reschedule Lapsed','DEO Pending','DEO >5'];const lines=[header,...sortedOfficers.map(r=>[r.officer,r.centre,r.contact,r.ps,r.totalNoMap,r.nmGen,r.nmPend,r.nmDel,r.nmPdel,r.hearings,r.hearingLapsed,r.rescheduleLapsed,r.deoPending,r.deo5])].map(a=>a.map(v=>`"${s(v).replaceAll('"','""')}"`).join(','));const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ECI_Officer_Location_No_Mapping_Report.csv';a.click();URL.revokeObjectURL(a.href)};
const reset=()=>{setQ('');setCentreFilter('All');setStatusFilter('All')};
const kpis=[['Total PS',430,'◫','All polling stations'],['Notice Generated',sum('Notice Generated'),'▣',`${((sum('Notice Generated')/Math.max(sum('Notice Generated')+sum('Pending for Notice Generation'),1))*100).toFixed(1)}% of total`],['Pending Generation',sum('Pending for Notice Generation'),'◷',`${((sum('Pending for Notice Generation')/Math.max(sum('Notice Generated')+sum('Pending for Notice Generation'),1))*100).toFixed(1)}% of total`],['Notice Delivered',sum('Notice Delivered'),'➤',`${((sum('Notice Delivered')/Math.max(sum('Notice Generated'),1))*100).toFixed(1)}% of generated`],['Pending Delivery',sum('Notice Pending Delivery'),'⌛',`${((sum('Notice Pending Delivery')/Math.max(sum('Notice Generated'),1))*100).toFixed(1)}% of generated`],['NO MAPPING TOTAL',totalNoMapping,'≋','Generated + Pending Generation']];
const action=[['Pending Generation',cats('nmPend'),()=>{setTab('Pending');setStatusFilter('PENDING')}],['Pending Delivery',cats('nmPdel'),()=>{setTab('Pending');setStatusFilter('PENDING')}],['Hearing Lapsed',sum('Hearing Date Lapsed'),()=>setTab('Hearings')],['Reschedule Lapsed',sum('Reschedule Date Lapsed'),()=>setTab('Hearings')],['DEO Pending',sum('DEO-Status Total Pending'),()=>setTab('DEO')],['DEO >5 Days',sum('DEO-Status Pending GT 5 Days'),()=>setTab('DEO')]] as Array<[string,number,()=>void]>;
const table=(rows:Joined[],state=psSort,setter=setPsSort)=><div className="tablewrap"><table><thead><tr>{th('PS','ps',state,setter)}{th('Old PS','oldPs',state,setter)}{th('BLO','blo',state,setter)}{th('Officer','officer',state,setter)}{th('Hearing Location','centre',state,setter)}<th colSpan={2}>GENERATED</th><th colSpan={2}>PENDING GENERATION</th><th colSpan={2}>DELIVERED</th><th colSpan={2}>PENDING DELIVERY</th>{th('Hearings','hearings',state,setter)}{th('DEO &gt;5','deo5',state,setter)}{th('Status','status',state,setter)}</tr><tr>{['anGen','nmGen','anPend','nmPend','anDel','nmDel','anPdel','nmPdel'].map((k,i)=><th key={k} className="sortable" onClick={()=>toggle(setter,state,k)}>{i%2?'NO MAP':'ANOM'}{arrow(state,k)}</th>)}</tr></thead><tbody>{sortJoined(rows,state).map(r=><tr key={r.ps} onClick={()=>setSelected(r)} className="clickRow"><td>{r.ps}</td><td>{r.m.oldPs??''}</td><td>{r.m.blo}</td><td>{r.map?.officer||r.m.officer}</td><td>{r.map?.centre||r.m.hearingCentre}</td><td className="anom">{fmt(r.cat.anGen)}</td><td className="nomap">{fmt(r.cat.nmGen)}</td><td className="anom">{fmt(r.cat.anPend)}</td><td className="nomap">{fmt(r.cat.nmPend)}</td><td className="anom">{fmt(r.cat.anDel)}</td><td className="nomap">{fmt(r.cat.nmDel)}</td><td className="anom">{fmt(r.cat.anPdel)}</td><td className="nomap">{fmt(r.cat.nmPdel)}</td><td>{fmt(fieldNum(r,'Hearings Held'))}</td><td>{fmt(fieldNum(r,'DEO-Status Pending GT 5 Days'))}</td><td><span className={`statusBadge ${status(r).toLowerCase()}`}>{status(r)}</span></td></tr>)}</tbody></table></div>;
const filters=<div className="filters"><input placeholder="Search PS / BLO / officer / location / locality / area..." value={q} onChange={e=>setQ(e.target.value)}/><select value={centreFilter} onChange={e=>setCentreFilter(e.target.value)}><option value="All">All Hearing Locations</option>{centres.map(c=><option key={c}>{c}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="All">All Status</option><option value="PENDING">PENDING</option><option value="CRITICAL">CRITICAL</option><option value="CLEAR">CLEAR</option></select><button className="resetSort" onClick={reset}>↻ Reset</button></div>;
const officerTable=<div className="tablewrap"><table><thead><tr>{th('Officer','officer',officerSort,setOfficerSort)}{th('Hearing Location','centre',officerSort,setOfficerSort)}{th('Contact','contact',officerSort,setOfficerSort)}{th('PS','ps',officerSort,setOfficerSort)}{th('TOTAL NO MAPPING','totalNoMap',officerSort,setOfficerSort)}{th('Generated','nmGen',officerSort,setOfficerSort)}{th('Pending Generation','nmPend',officerSort,setOfficerSort)}{th('Delivered','nmDel',officerSort,setOfficerSort)}{th('Pending Delivery','nmPdel',officerSort,setOfficerSort)}{th('Hearings','hearings',officerSort,setOfficerSort)}{th('Hearing Lapsed','hearingLapsed',officerSort,setOfficerSort)}{th('Reschedule Lapsed','rescheduleLapsed',officerSort,setOfficerSort)}{th('DEO Pending','deoPending',officerSort,setOfficerSort)}{th('DEO &gt;5','deo5',officerSort,setOfficerSort)}</tr></thead><tbody>{sortedOfficers.map(r=><tr key={`${r.officer}|${r.centre}`}><td><b>{r.officer}</b></td><td>{r.centre}</td><td>{r.contact}</td><td>{r.ps}</td><td className="nomap"><b>{fmt(r.totalNoMap)}</b></td><td className="nomap">{fmt(r.nmGen)}</td><td className="nomap">{fmt(r.nmPend)}</td><td className="nomap">{fmt(r.nmDel)}</td><td className="nomap">{fmt(r.nmPdel)}</td><td>{fmt(r.hearings)}</td><td>{fmt(r.hearingLapsed)}</td><td>{fmt(r.rescheduleLapsed)}</td><td>{fmt(r.deoPending)}</td><td>{fmt(r.deo5)}</td></tr>)}</tbody></table></div>;
return <main className="app"><header className="topbar"><div className="brandRow"><div className="eciMark">⚖</div><div><div className="brand">ECI HEARING & NOTICE MONITORING</div><div className="sub">NCT OF DELHI · 430 POLLING STATIONS · OPERATIONAL CONTROL ROOM</div></div></div><div className="headerRight"><div className="live"><div>{updated?`Last upload: ${updated}`:'No ECI upload yet'}</div><div className="liveLine"><span className="dot"/> Data loaded successfully</div></div><button className={`iconBtn ${autoRefresh?'on':''}`} onClick={()=>setAutoRefresh(v=>!v)} title="Auto refresh">↻</button><button className="iconBtn" onClick={()=>exportRows(filtered,'ECI_Hearing_Detailed_Report.csv')} title="Download detailed report">⇩</button><button className="adminBtn"><span className="avatar">A</span> Admin⌄</button></div></header><div className="wrap"><div className="toolbar"><div className="upload"><label>Upload ECI Excel<input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'eci')}/></label><label>Load Master (one-time)<input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'master')}/></label></div><div className="notice">Recurring: download ECI → upload latest Excel → dashboard updates. {autoRefresh&&'Auto-refresh is ON.'}</div></div>{error&&<div className="notice errorNotice">{error}</div>}{!master.length&&<div className="notice">First time only: load <b>For Hearing Schedule-3.xlsx</b>. It stays in this browser; after that, only ECI uploads are needed.</div>}
<nav className="tabs">{['Overview','PS Wise','Hearing Centres','Officer Wise','Pending','Hearings','DEO','Validation','Reports','History','Settings'].map(t=><button className={`tab ${tab===t?'active':''}`} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>
{tab==='Overview'&&<><div className="grid">{kpis.map(([l,v,i,m])=><button className="card kpiButton" key={l} onClick={()=>l==='NO MAPPING TOTAL'?setTab('Officer Wise'):undefined}><div className="cardTop"><div className="cardIcon">{i}</div><div><div className="label">{l}</div><div className="value">{fmt(Number(v))}</div><div className="meta">{m}</div></div></div></button>)}</div><div className="actionPanel"><div className="actionTitle">TODAY'S ACTION REQUIRED</div><div className="actionGrid">{action.map(([l,v,go])=><button key={l} className={v>0?'actionItem hot':'actionItem'} onClick={go}><span>{l}</span><b>{fmt(v)}</b></button>)}</div></div><div className="section"><h2>Notice status — ANOMALY and NO MAPPING shown separately</h2><div className="split">{([['ANOMALY','anGen','anPend','anDel','anPdel'],['NO MAPPING','nmGen','nmPend','nmDel','nmPdel'],['ECI TOTAL','gen','pgen','del','pdel']] as Array<[string,keyof Cat,keyof Cat,keyof Cat,keyof Cat]>).map(x=><div className={`mini ${x[0]==='ANOMALY'?'anomalyMini':x[0]==='NO MAPPING'?'mappingMini':'totalMini'}`} key={x[0]}><h3>{x[0]}</h3>{[['Generated',x[1]],['Pending Gen',x[2]],['Delivered',x[3]],['Pending Del',x[4]]].map(([l,k])=><div className="metricrow" key={l}><span>{l}</span><b>{fmt(cats(k as keyof Cat))}</b></div>)}{x[0]==='NO MAPPING'&&<div className="metricrow"><span>Total Notices</span><b>{fmt(totalNoMapping)}</b></div>}</div>)}</div></div><div className="secondary">{[['Hearings Held',sum('Hearings Held')],['Hearing Lapsed',sum('Hearing Date Lapsed')],['Reschedule Lapsed',sum('Reschedule Date Lapsed')],['DEO Pending',sum('DEO-Status Total Pending')],['DEO > 5 Days',sum('DEO-Status Pending GT 5 Days')]].map(([l,v])=><button className="secondaryItem" key={l} onClick={()=>l==='DEO Pending'||l==='DEO > 5 Days'?setTab('DEO'):l==='Hearings Held'||l==='Hearing Lapsed'||l==='Reschedule Lapsed'?setTab('Hearings'):undefined}><span>{l}</span><b>{fmt(Number(v))}</b></button>)}</div><div className="section"><div className="sectionHead"><div><h2>PS-Wise Status — Separate ANOMALY / NO MAPPING Notices</h2><div className="hint">Click any row for complete PS, NO MAPPING, hearing and DEO details.</div></div><button className="resetSort" onClick={()=>exportRows(filtered,'ECI_Hearing_Detailed_Report.csv')}>⇩ Export</button></div>{filters}{table(filtered)}</div></>}
{tab==='PS Wise'&&<div className="section"><div className="sectionHead"><div><h2>PS-Wise Operational Register</h2><div className="hint">430 PS records · click any row for the full operational detail.</div></div><button className="resetSort" onClick={()=>exportRows(filtered,'ECI_Hearing_Detailed_Report.csv')}>⇩ Export</button></div>{filters}{table(filtered)}</div>}
{tab==='Hearing Centres'&&<div className="section"><div className="sectionHead"><div><h2>Hearing Centre Reconciliation — NO MAPPING Focus</h2><div className="hint">Every hearing location is independently reconciled.</div></div><button className="resetSort" onClick={()=>exportRows(filtered,'ECI_Hearing_Detailed_Report.csv')}>⇩ Export</button></div><div className="tablewrap"><table><thead><tr>{th('Hearing Centre','centre',centreSort,setCentreSort)}<th>Officer</th><th>Contact</th><th>PS</th><th>Total No Mapping</th><th>Generated</th><th>Pending Generation</th><th>Delivered</th><th>Pending Delivery</th><th>DEO &gt;5</th></tr></thead><tbody>{sortedCentres.map(r=><tr key={r.centre}><td><b>{r.centre}</b></td><td>{r.officer}</td><td>{r.contact}</td><td>{r.ps}</td><td className="nomap"><b>{fmt(r.total)}</b></td><td className="nomap">{fmt(r.gen)}</td><td className="nomap">{fmt(r.pend)}</td><td className="nomap">{fmt(r.del)}</td><td className="nomap">{fmt(r.pdel)}</td><td>{fmt(r.deo5)}</td></tr>)}</tbody></table></div></div>}
{tab==='Officer Wise'&&<div className="section"><div className="sectionHead"><div><h2>Officer-wise NO MAPPING Notice Reconciliation</h2><div className="hint">Each officer-location combination is a separate row. One officer with two hearing locations appears twice, with complete NO MAPPING details.</div></div><button className="resetSort" onClick={exportOfficer}>⇩ Export Officer Report</button></div><div className="summaryStrip"><div><span>Total NO MAPPING Notices</span><b>{fmt(totalNoMapping)}</b></div><div><span>Officer / Location Rows</span><b>{sortedOfficers.length}</b></div><div><span>NO MAPPING Generated</span><b>{fmt(cats('nmGen'))}</b></div><div><span>NO MAPPING Pending Generation</span><b>{fmt(cats('nmPend'))}</b></div><div><span>NO MAPPING Delivered</span><b>{fmt(cats('nmDel'))}</b></div><div><span>NO MAPPING Pending Delivery</span><b>{fmt(cats('nmPdel'))}</b></div></div><div className="officerSummary"><div className="panelTitle">OFFICER TOTALS — all hearing locations combined</div><div className="officerCards">{officerTotals.map(x=><button key={x.officer} className="officerCard" onClick={()=>{setQ(x.officer);setTab('PS Wise')}}><div><b>{x.officer}</b><span>{x.locations} location{x.locations===1?'':'s'} · {x.ps} PS</span></div><strong>{fmt(x.total)}</strong><small>NO MAPPING · {fmt(x.gen)} generated · {fmt(x.pend)} pending gen · {fmt(x.del)} delivered · {fmt(x.pdel)} pending delivery</small></button>)}</div></div>{officerTable}</div>}
{tab==='Pending'&&<div className="section"><div className="sectionHead"><div><h2>Operational Pending Report — Separate NO MAPPING / ANOMALY</h2><div className="hint">Generation, delivery, lapsed hearing and DEO pending are kept as separate operational stages.</div></div><button className="resetSort" onClick={()=>exportRows(filtered.filter(r=>r.cat.anPend+r.cat.nmPend+r.cat.nmPdel+fieldNum(r,'Hearing Date Lapsed')+fieldNum(r,'Reschedule Date Lapsed')+fieldNum(r,'DEO-Status Total Pending')>0),'ECI_Pending_Report.csv')}>⇩ Export Pending</button></div>{filters}{table(filtered.filter(r=>r.cat.anPend+r.cat.nmPend+r.cat.nmPdel+fieldNum(r,'Hearing Date Lapsed')+fieldNum(r,'Reschedule Date Lapsed')+fieldNum(r,'DEO-Status Total Pending')>0))}</div>}
{tab==='Hearings'&&<div className="section"><div className="sectionHead"><div><h2>Hearing Calendar & Progress</h2><div className="hint">Dates are read from the uploaded ECI workbook; no dates are invented.</div></div><button className="resetSort" onClick={()=>exportRows(hearings.map(x=>x.r),'ECI_Hearing_Calendar_Source.csv')}>⇩ Export</button></div><div className="summaryStrip"><div><span>Hearings Held</span><b>{fmt(sum('Hearings Held'))}</b></div><div><span>Hearing Lapsed</span><b>{fmt(sum('Hearing Date Lapsed'))}</b></div><div><span>Reschedule Lapsed</span><b>{fmt(sum('Reschedule Date Lapsed'))}</b></div><div><span>Scheduled/dated PS</span><b>{fmt(hearings.length)}</b></div></div><div className="tablewrap"><table><thead><tr><th>PS</th><th>Officer</th><th>Hearing Location</th><th>Hearing Date</th><th>Reschedule Date</th><th>Held</th><th>Hearing Lapsed</th><th>Reschedule Lapsed</th><th>NO MAPPING</th></tr></thead><tbody>{hearings.map(x=><tr key={x.r.ps}><td>{x.r.ps}</td><td>{x.r.map?.officer}</td><td>{x.r.map?.centre}</td><td>{x.date||'—'}</td><td>{x.reschedule||'—'}</td><td>{fmt(x.held)}</td><td>{fmt(x.lapsed)}</td><td>{fmt(x.resLapsed)}</td><td className="nomap"><b>{fmt(x.r.cat.nmGen+x.r.cat.nmPend)}</b></td></tr>)}</tbody></table></div></div>}
{tab==='DEO'&&<div className="section"><div className="sectionHead"><div><h2>DEO Action Tracking</h2><div className="hint">Only records with DEO pending / ageing values are shown.</div></div><button className="resetSort" onClick={()=>exportRows(deoRows,'ECI_DEO_Pending_Report.csv')}>⇩ Export DEO</button></div><div className="summaryStrip"><div><span>DEO Pending</span><b>{fmt(sum('DEO-Status Total Pending'))}</b></div><div><span>DEO &gt;5 Days</span><b>{fmt(sum('DEO-Status Pending GT 5 Days'))}</b></div><div><span>Records</span><b>{fmt(deoRows.length)}</b></div></div><div className="tablewrap"><table><thead><tr><th>PS</th><th>BLO</th><th>Officer</th><th>Hearing Location</th><th>NO MAPPING</th><th>DEO Pending</th><th>DEO &gt;5 Days</th><th>Status</th></tr></thead><tbody>{deoRows.map(r=><tr key={r.ps} className="clickRow" onClick={()=>setSelected(r)}><td>{r.ps}</td><td>{r.m.blo}</td><td>{r.map?.officer}</td><td>{r.map?.centre}</td><td className="nomap"><b>{fmt(r.cat.nmGen+r.cat.nmPend)}</b></td><td>{fmt(fieldNum(r,'DEO-Status Total Pending'))}</td><td>{fmt(fieldNum(r,'DEO-Status Pending GT 5 Days'))}</td><td><span className={`statusBadge ${status(r).toLowerCase()}`}>{status(r)}</span></td></tr>)}</tbody></table></div></div>}
{tab==='Validation'&&<div className="section"><div className="sectionHead"><div><h2>Data Validation & Reconciliation</h2><div className="hint">No source values are silently altered. Allocation uses the confirmed NO MAPPING first → ANOMALY rule.</div></div></div><div className="validationTable"><table><thead><tr><th>Check</th><th>Actual</th><th>Expected</th><th>Result</th></tr></thead><tbody>{validation.map(([label,actual,expected,ok])=><tr key={label}><td>{label}</td><td>{fmt(actual)}</td><td>{fmt(expected)}</td><td><span className={`statusBadge ${ok?'clear':'critical'}`}>{ok?'PASS':'CHECK'}</span></td></tr>)}</tbody></table></div></div>}
{tab==='Reports'&&<div className="section reports"><div className="sectionHead"><div><h2>Reports & Exports</h2><div className="hint">Download exactly the operational slice you need.</div></div></div><div className="reportGrid"><button onClick={()=>exportRows(joined,'ECI_All_PS_Detailed_Report.csv')}>PS-wise Detailed Report <span>430 PS</span></button><button onClick={exportOfficer}>Officer + Hearing Location Report <span>{sortedOfficers.length} rows</span></button><button onClick={()=>exportRows(joined.filter(r=>r.cat.nmGen+r.cat.nmPend>0),'ECI_All_No_Mapping_Report.csv')}>NO MAPPING Full Report <span>{fmt(totalNoMapping)} notices</span></button><button onClick={()=>exportRows(joined.filter(r=>r.cat.nmPend>0),'ECI_No_Mapping_Pending_Generation.csv')}>NO MAPPING Pending Generation <span>{fmt(cats('nmPend'))}</span></button><button onClick={()=>exportRows(joined.filter(r=>r.cat.nmPdel>0),'ECI_No_Mapping_Pending_Delivery.csv')}>NO MAPPING Pending Delivery <span>{fmt(cats('nmPdel'))}</span></button><button onClick={()=>exportRows(deoRows,'ECI_DEO_Pending_Report.csv')}>DEO Pending Report <span>{fmt(sum('DEO-Status Total Pending'))}</span></button></div></div>}
{tab==='History'&&<div className="section"><div className="sectionHead"><div><h2>Upload History</h2><div className="hint">Recent ECI uploads are retained locally in this browser for operational comparison.</div></div></div><div className="tablewrap"><table><thead><tr><th>Upload Time</th><th>Type</th><th>PS Rows</th><th>Generated</th><th>Pending Generation</th><th>Delivered</th><th>Pending Delivery</th></tr></thead><tbody>{history.length?history.map((h,i)=><tr key={`${h.time}-${i}`}><td>{h.time}</td><td>{h.kind}</td><td>{h.rows}</td><td>{fmt(h.generated)}</td><td>{fmt(h.pending)}</td><td>{fmt(h.delivered)}</td><td>{fmt(h.pendingDelivery)}</td></tr>):<tr><td colSpan={7}>No upload history recorded yet.</td></tr>}</tbody></table></div><div className="historyInfo">Master data: <b>{master.length===430?'Loaded · 430 PS':'Not loaded'}</b> · Current ECI: <b>{eci.length===430?'Loaded · 430 PS':'Not loaded'}</b></div></div>}
{tab==='Settings'&&<div className="section infoPanel"><h2>Dashboard Settings & Operating Rules</h2><div className="historyRow"><span>Theme</span><b>Dark / Operations</b></div><div className="historyRow"><span>Category allocation</span><b>NO MAPPING first → ANOMALY</b></div><div className="historyRow"><span>Operational scope</span><b>430 Polling Stations · NCT of Delhi</b></div><div className="historyRow"><span>Auto refresh</span><button className="resetSort" onClick={()=>setAutoRefresh(v=>!v)}>{autoRefresh?'ON · 30 sec':'OFF'}</button></div><div className="historyRow"><span>Stored master</span><b>{master.length===430?'Available in this browser':'Not loaded'}</b></div></div>}
<div className="footer">Election Commission of India — SIR Hearing & Notice Monitoring &nbsp;|&nbsp; NCT of Delhi</div></div>
{selected&&<div className="modalBackdrop" onClick={()=>setSelected(null)}><div className="detailModal" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><h2>PS {selected.ps} — Complete Operational Detail</h2><div>{selected.m.blo} · {selected.map?.officer} · {selected.map?.centre}</div></div><button onClick={()=>setSelected(null)}>✕</button></div><div className="detailGrid"><div><span>Old PS</span><b>{selected.m.oldPs??'—'}</b></div><div><span>Contact</span><b>{selected.map?.contact||'—'}</b></div><div><span>Locality</span><b>{selected.m.locality||'—'}</b></div><div><span>Polling Area</span><b>{selected.m.pollingArea||'—'}</b></div></div><div className="detailSection"><h3>NO MAPPING — complete lifecycle</h3><div className="detailMetrics"><div><span>Total</span><b>{fmt(selected.cat.nmGen+selected.cat.nmPend)}</b></div><div><span>Generated</span><b>{fmt(selected.cat.nmGen)}</b></div><div><span>Pending Generation</span><b>{fmt(selected.cat.nmPend)}</b></div><div><span>Delivered</span><b>{fmt(selected.cat.nmDel)}</b></div><div><span>Pending Delivery</span><b>{fmt(selected.cat.nmPdel)}</b></div></div></div><div className="detailSection"><h3>Hearing / DEO</h3><div className="detailRows"><div><span>Hearing Date</span><b>{s(field(selected,'Hearing Date','Hearing date','HEARING DATE'))||'—'}</b></div><div><span>Hearings Held</span><b>{fmt(fieldNum(selected,'Hearings Held'))}</b></div><div><span>Hearing Lapsed</span><b>{fmt(fieldNum(selected,'Hearing Date Lapsed'))}</b></div><div><span>Reschedule Lapsed</span><b>{fmt(fieldNum(selected,'Reschedule Date Lapsed'))}</b></div><div><span>DEO Pending</span><b>{fmt(fieldNum(selected,'DEO-Status Total Pending'))}</b></div><div><span>DEO &gt;5 Days</span><b>{fmt(fieldNum(selected,'DEO-Status Pending GT 5 Days'))}</b></div></div></div><div className="detailSection"><h3>Polling Station</h3><p>{selected.m.address||'Address not available in loaded master.'}</p></div></div></div>}
</main>}
