'use client';
import {useEffect,useMemo,useState} from 'react';
import * as XLSX from 'xlsx';

type Master={ps:number;oldPs:number|null;anomaly:number;mapping:number;grandTotal:number;blo:string;supervisor:string;officer:string;hearingCentre:string;address:string;locality:string;pollingArea:string;voters:number};
type Eci=Record<string,unknown>&{ps:number};
type MapRow={centre:string;officer:string;contact:string};
type Cat={anGen:number;nmGen:number;anPend:number;nmPend:number;anDel:number;nmDel:number;anPdel:number;nmPdel:number;gen:number;pgen:number;del:number;pdel:number};
type Joined=Eci&{m:Master;cat:Cat;map:MapRow|null};
type SortDir='asc'|'desc'; type SortState={key:string;dir:SortDir};
const MAP:Array<[string,number,number,string,string]>=[
['GCSSS, SEC-3 DWARKA(P)',1,50,'SH. PARVEEN KUMAR','9953601073'],['GCSSS, SEC-3 DWARKA(P)',55,60,'SH. PARVEEN KUMAR','9953601073'],['GCSSS, SEC-3 DWARKA(P)',78,79,'SH. PARVEEN KUMAR','9953601073'],['GCSSS, SEC-3 DWARKA(P)',91,96,'SH. PARVEEN KUMAR','9953601073'],
['GCSSS, SEC-3 DWARKA(S)',51,54,'SMT. SHASHI BALA','9953312984'],['GCSSS, SEC-3 DWARKA(S)',61,77,'SMT. SHASHI BALA','9953312984'],['GCSSS, SEC-3 DWARKA(S)',80,90,'SMT. SHASHI BALA','9953312984'],['GCSSS, SEC-3 DWARKA(S)',97,109,'SMT. SHASHI BALA','9953312984'],['GCSSS, SEC-3 DWARKA(S)',135,145,'SMT. SHASHI BALA','9953312984'],
['GCSSC SEC-22 DWARKA(R)',110,134,'SH. RAKESH KUMAR','7011971522'],['GCSSC SEC-22 DWARKA(R)',331,341,'SH. RAKESH KUMAR','7011971522'],['GCSSC SEC-22 DWARKA(R)',343,344,'SH. RAKESH KUMAR','7011971522'],['GCSSC SEC-22 DWARKA(R)',347,349,'SH. RAKESH KUMAR','7011971522'],
['VREC MATIALA',146,234,'SMT. PARUL GUPTA','9667881989'],['VREC MATIALA',276,288,'SMT. PARUL GUPTA','9667881989'],['MCD BOYS PRIMARY SCHOOL, QUTUB VIHAR',235,275,'SH. SUBHASHISH','9868252144'],['MCD BOYS PRIMARY SCHOOL, QUTUB VIHAR',289,330,'SH. SUBHASHISH','9868252144'],
['GCSSS SEC 22 DWARKA(V)',342,342,'SH. VIRENDER','9868252144'],['GCSSS SEC 22 DWARKA(V)',345,346,'SH. VIRENDER','9868252144'],['GCSSS SEC 22 DWARKA(V)',350,374,'SH. VIRENDER','9868252144'],['GCSSS GHUMANHERA',375,430,'SH. VIRENDER','9868252144']];
const centres=[...new Set(MAP.map(x=>x[0]))];
const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:0}; const s=(v:unknown)=>String(v??'').trim(); const key=(v:unknown)=>s(v).toLowerCase();
const centre=(ps:number):MapRow|null=>{const x=MAP.find(m=>ps>=m[1]&&ps<=m[2]);return x?{centre:x[0],officer:x[3],contact:x[4]}:null};
function parseEci(rows:unknown[][]):Eci[]{if(!rows.length)return[];const heads=rows[0].map(s),ix=(x:string)=>heads.indexOf(x),p=ix('POLLING STATION');if(p<0)throw Error('ECI sheet is missing the POLLING STATION column.');return rows.slice(1).filter(r=>r.some(v=>s(v)!=='')).map(r=>{const o:Record<string,unknown>={};heads.forEach((h,i)=>{if(h)o[h]=r[i]});o.ps=Math.trunc(n(r[p]));return o as Eci}).filter(r=>r.ps>=1&&r.ps<=430)}
function parseMaster(rows:unknown[][]):Master[]{if(rows.length<3)return[];const heads=rows[1].map(s),ix=(x:string)=>heads.indexOf(x);const req=['New P.S. No.','Old P.S. No.','Total Anamoly/Discripancy','Total No Mapping','Grand Total','All BLO Name','Supervisor Name','Officer Name (NEW)','Hearing Centre','Address of P.S.','LOCALITY','POLLING AREA','Total Voters'];const miss=req.filter(x=>ix(x)<0);if(miss.length)throw Error(`Master sheet is missing: ${miss.join(', ')}`);return rows.slice(2).filter(r=>r[ix('New P.S. No.')]!==''&&r[ix('New P.S. No.')]!=null).map(r=>({ps:Math.trunc(n(r[ix('New P.S. No.')])),oldPs:r[ix('Old P.S. No.')]===''?null:n(r[ix('Old P.S. No.')]),anomaly:n(r[ix('Total Anamoly/Discripancy')]),mapping:n(r[ix('Total No Mapping')]),grandTotal:n(r[ix('Grand Total')]),blo:s(r[ix('All BLO Name')]),supervisor:s(r[ix('Supervisor Name')]),officer:s(r[ix('Officer Name (NEW)')]),hearingCentre:s(r[ix('Hearing Centre')]),address:s(r[ix('Address of P.S.')]),locality:s(r[ix('LOCALITY')]),pollingArea:s(r[ix('POLLING AREA')]),voters:n(r[ix('Total Voters')])}))}
function category(e:Eci,m:Master):Cat{const gen=Math.max(n(e['Notice Generated']),0),pgen=Math.max(n(e['Pending for Notice Generation']),0),del=Math.max(n(e['Notice Delivered']),0),pdel=Math.max(n(e['Notice Pending Delivery']),0);const nmGen=Math.min(gen,Math.max(m.mapping,0)),anGen=Math.min(Math.max(gen-nmGen,0),Math.max(m.anomaly,0)),nmPend=Math.min(pgen,Math.max(m.mapping-nmGen,0)),anPend=Math.min(Math.max(pgen-nmPend,0),Math.max(m.anomaly-anGen,0)),nmDel=Math.min(del,nmGen),anDel=Math.min(Math.max(del-nmDel,0),anGen),nmPdel=Math.min(pdel,Math.max(nmGen-nmDel,0)),anPdel=Math.min(Math.max(pdel-nmPdel,0),Math.max(anGen-anDel,0));return{anGen,nmGen,anPend,nmPend,anDel,nmDel,anPdel,nmPdel,gen,pgen,del,pdel}}
function status(r:Joined){if(n(r['DEO-Status Pending GT 5 Days'])>0||n(r['Hearing Date Lapsed'])>0||n(r['Reschedule Date Lapsed'])>0)return'CRITICAL';if(n(r['Pending for Notice Generation'])>0||n(r['Notice Pending Delivery'])>0||n(r['DEO-Status Total Pending'])>0)return'PENDING';return'CLEAR'}
export default function Dashboard(){
const[master,setMaster]=useState<Master[]>([]),[eci,setEci]=useState<Eci[]>([]),[tab,setTab]=useState('Overview'),[q,setQ]=useState(''),[centreFilter,setCentreFilter]=useState('All'),[updated,setUpdated]=useState(''),[error,setError]=useState('');
const[psSort,setPsSort]=useState<SortState>({key:'ps',dir:'asc'}),[centreSort,setCentreSort]=useState<SortState>({key:'centre',dir:'asc'}),[validationSort,setValidationSort]=useState<SortState>({key:'label',dir:'asc'});
useEffect(()=>{try{const m=localStorage.getItem('eci-master'),e=localStorage.getItem('eci-current'),t=localStorage.getItem('eci-updated');if(m)setMaster(JSON.parse(m));if(e)setEci(JSON.parse(e));if(t)setUpdated(t)}catch{setError('Saved browser data could not be read.')}},[]);
const upload=async(file:File,type:'eci'|'master')=>{setError('');try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),ws=type==='eci'?(wb.Sheets['sirNoticeGenerate']||wb.Sheets[wb.SheetNames[0]]):(wb.Sheets['Rough Data']||wb.Sheets[wb.SheetNames[0]]);if(!ws)throw Error('Required worksheet was not found.');const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''}) as unknown[][];if(type==='eci'){const p=parseEci(rows),u=new Set(p.map(x=>x.ps));if(p.length!==430||u.size!==430)throw Error(`ECI file has ${p.length} unique valid PS rows; expected 430.`);setEci(p);const now=new Date().toLocaleString('en-IN',{hour12:false});setUpdated(now);localStorage.setItem('eci-current',JSON.stringify(p));localStorage.setItem('eci-updated',now)}else{const p=parseMaster(rows),u=new Set(p.map(x=>x.ps));if(p.length!==430||u.size!==430)throw Error(`Master file has ${p.length} unique valid PS rows; expected 430.`);setMaster(p);localStorage.setItem('eci-master',JSON.stringify(p))}}catch(e){setError(e instanceof Error?e.message:'Could not read workbook.')}};
const joined=useMemo<Joined[]>(()=>{const mm=new Map(master.map(m=>[m.ps,m]));return eci.map(e=>{const m=mm.get(e.ps)||{ps:e.ps,oldPs:null,anomaly:0,mapping:0,grandTotal:0,blo:'',supervisor:'',officer:'',hearingCentre:'',address:'',locality:'',pollingArea:'',voters:0};return{...e,m,cat:category(e,m),map:centre(e.ps)}})},[eci,master]);
const filtered=joined.filter(r=>(centreFilter==='All'||r.map?.centre===centreFilter)&&(q===''||String(r.ps).includes(q)||key(r.m.blo).includes(key(q))||key(r.m.locality).includes(key(q))||key(r.m.pollingArea).includes(key(q))));
const sum=(k:string)=>joined.reduce((a,r)=>a+n(r[k]),0),cats=(k:keyof Cat)=>joined.reduce((a,r)=>a+n(r.cat[k]),0),fmt=(v:number)=>v.toLocaleString('en-IN');
const valJoined=(r:Joined,k:string):unknown=>({ps:r.ps,oldPs:r.m.oldPs??-1,blo:r.m.blo,officer:r.map?.officer||r.m.officer,centre:r.map?.centre||r.m.hearingCentre,anGen:r.cat.anGen,nmGen:r.cat.nmGen,anPend:r.cat.anPend,nmPend:r.cat.nmPend,anDel:r.cat.anDel,nmDel:r.cat.nmDel,anPdel:r.cat.anPdel,nmPdel:r.cat.nmPdel,hearings:n(r['Hearings Held']),deo5:n(r['DEO-Status Pending GT 5 Days']),status:status(r)}[k]);
const compare=(av:unknown,bv:unknown)=>{const an=typeof av==='number'?av:Number(av),bn=typeof bv==='number'?bv:Number(bv);return Number.isFinite(an)&&Number.isFinite(bn)?an-bn:s(av).localeCompare(s(bv),undefined,{numeric:true,sensitivity:'base'})};
const sortJoined=(rows:Joined[],state=psSort)=>[...rows].sort((a,b)=>(state.dir==='asc'?1:-1)*compare(valJoined(a,state.key),valJoined(b,state.key)));
const toggle=(setter:React.Dispatch<React.SetStateAction<SortState>>,state:SortState,k:string)=>setter(state.key===k?{key:k,dir:state.dir==='asc'?'desc':'asc'}:{key:k,dir:'asc'});
const arrow=(state:SortState,k:string)=>state.key===k?(state.dir==='asc'?' ↑':' ↓'):' ↕';
const th=(label:string,k:string,state:SortState,setter:React.Dispatch<React.SetStateAction<SortState>>,rs=2)=><th rowSpan={rs} className="sortable" onClick={()=>toggle(setter,state,k)}>{label}{arrow(state,k)}</th>;
const centreRows=useMemo(()=>centres.map(c=>{const rs=joined.filter(r=>r.map?.centre===c);return{centre:c,officer:rs[0]?.map?.officer||'',contact:rs[0]?.map?.contact||'',ps:rs.length,anGen:rs.reduce((a,r)=>a+r.cat.anGen,0),nmGen:rs.reduce((a,r)=>a+r.cat.nmGen,0),anPend:rs.reduce((a,r)=>a+r.cat.anPend,0),nmPend:rs.reduce((a,r)=>a+r.cat.nmPend,0),anDel:rs.reduce((a,r)=>a+r.cat.anDel,0),nmDel:rs.reduce((a,r)=>a+r.cat.nmDel,0),anPdel:rs.reduce((a,r)=>a+r.cat.anPdel,0),nmPdel:rs.reduce((a,r)=>a+r.cat.nmPdel,0),deo5:rs.reduce((a,r)=>a+n(r['DEO-Status Pending GT 5 Days']),0)}}),[joined]);
const sortedCentres=useMemo(()=>[...centreRows].sort((a,b)=>(centreSort.dir==='asc'?1:-1)*compare((a as Record<string,unknown>)[centreSort.key],(b as Record<string,unknown>)[centreSort.key])),[centreRows,centreSort]);
const kpis=[['Total PS',430,'◫','All polling stations'],['Notice Generated',sum('Notice Generated'),'▣',`${((sum('Notice Generated')/Math.max(sum('Notice Generated')+sum('Pending for Notice Generation'),1))*100).toFixed(1)}% of total`],['Pending Generation',sum('Pending for Notice Generation'),'◷',`${((sum('Pending for Notice Generation')/Math.max(sum('Notice Generated')+sum('Pending for Notice Generation'),1))*100).toFixed(1)}% of total`],['Notice Delivered',sum('Notice Delivered'),'➤',`${((sum('Notice Delivered')/Math.max(sum('Notice Generated'),1))*100).toFixed(1)}% of generated`],['Pending Delivery',sum('Notice Pending Delivery'),'⌛',`${((sum('Notice Pending Delivery')/Math.max(sum('Notice Generated'),1))*100).toFixed(1)}% of generated`]];
const secondary=[['Hearings Held',sum('Hearings Held')],['Hearing Lapsed',sum('Hearing Date Lapsed')],['Reschedule Lapsed',sum('Reschedule Date Lapsed')],['DEO Pending',sum('DEO-Status Total Pending')],['DEO > 5 Days',sum('DEO-Status Pending GT 5 Days')]];
const validation=[['ECI PS count',eci.length,430,eci.length===430],['Master PS count',master.length,430,master.length===430],['Generated split',cats('anGen')+cats('nmGen'),sum('Notice Generated'),cats('anGen')+cats('nmGen')===sum('Notice Generated')],['Pending generation split',cats('anPend')+cats('nmPend'),sum('Pending for Notice Generation'),cats('anPend')+cats('nmPend')===sum('Pending for Notice Generation')],['Delivered split',cats('anDel')+cats('nmDel'),sum('Notice Delivered'),cats('anDel')+cats('nmDel')===sum('Notice Delivered')],['Pending delivery split',cats('anPdel')+cats('nmPdel'),sum('Notice Pending Delivery'),cats('anPdel')+cats('nmPdel')===sum('Notice Pending Delivery')]] as Array<[string,number,number,boolean]>;
const sortedValidation=useMemo(()=>[...validation].sort((a,b)=>(validationSort.dir==='asc'?1:-1)*compare(a[0],b[0])),[validation,validationSort]);
const exportCsv=()=>{const rows=sortJoined(filtered);const header=['PS','Old PS','BLO','Centre','Gen Anom','Gen No Map','Pend Gen Anom','Pend Gen No Map','Del Anom','Del No Map','Pend Del Anom','Pend Del No Map','Hearings','DEO >5','Status'];const lines=[header,...rows.map(r=>[r.ps,r.m.oldPs??'',r.m.blo,r.map?.centre||r.m.hearingCentre,r.cat.anGen,r.cat.nmGen,r.cat.anPend,r.cat.nmPend,r.cat.anDel,r.cat.nmDel,r.cat.anPdel,r.cat.nmPdel,n(r['Hearings Held']),n(r['DEO-Status Pending GT 5 Days']),status(r)])].map(a=>a.map(v=>`"${s(v).replaceAll('"','""')}"`).join(','));const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ECI_Hearing_Report.csv';a.click();URL.revokeObjectURL(a.href)};
const table=(rows:Joined[],state=psSort,setter=setPsSort)=><div className="tablewrap"><table><thead><tr>{th('PS','ps',state,setter)}{th('Old PS','oldPs',state,setter)}{th('BLO','blo',state,setter)}{th('Centre','centre',state,setter)}<th colSpan={2}>GENERATED</th><th colSpan={2}>PENDING GENERATION</th><th colSpan={2}>DELIVERED</th><th colSpan={2}>PENDING DELIVERY</th>{th('Hearings','hearings',state,setter)}{th('DEO >5','deo5',state,setter)}{th('Status','status',state,setter)}</tr><tr>{['anGen','nmGen','anPend','nmPend','anDel','nmDel','anPdel','nmPdel'].map((k,i)=><th key={k} className="sortable" onClick={()=>toggle(setter,state,k)}>{i%2?'NO MAP':'ANOM'}{arrow(state,k)}</th>)}</tr></thead><tbody>{sortJoined(rows,state).map(r=><tr key={r.ps}><td>{r.ps}</td><td>{r.m.oldPs??''}</td><td>{r.m.blo}</td><td>{r.map?.centre||r.m.hearingCentre}</td><td className="anom">{fmt(r.cat.anGen)}</td><td className="nomap">{fmt(r.cat.nmGen)}</td><td className="anom">{fmt(r.cat.anPend)}</td><td className="nomap">{fmt(r.cat.nmPend)}</td><td className="anom">{fmt(r.cat.anDel)}</td><td className="nomap">{fmt(r.cat.nmDel)}</td><td className="anom">{fmt(r.cat.anPdel)}</td><td className="nomap">{fmt(r.cat.nmPdel)}</td><td>{fmt(n(r['Hearings Held']))}</td><td>{fmt(n(r['DEO-Status Pending GT 5 Days']))}</td><td><span className={`statusBadge ${status(r).toLowerCase()}`}>{status(r)}</span></td></tr>)}</tbody></table></div>;
return <main className="app"><header className="topbar"><div className="brandRow"><div className="eciMark">⚖</div><div><div className="brand">ECI HEARING & NOTICE MONITORING</div><div className="sub">NCT OF DELHI · 430 POLLING STATIONS · LIVE ECI UPLOAD DASHBOARD</div></div></div><div className="headerRight"><div className="live"><div>{updated?`Last upload: ${updated}`:'No ECI upload yet'}</div><div className="liveLine"><span className="dot"/> Data loaded successfully</div></div><button className="iconBtn" title="Dark theme">☾</button><button className="iconBtn" onClick={exportCsv} title="Download report">⇩</button><button className="adminBtn"><span className="avatar">A</span> Admin⌄</button></div></header><div className="wrap"><div className="toolbar"><div className="upload"><label>Upload ECI Excel<input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'eci')}/></label><label>Load Master (one-time)<input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'master')}/></label></div><div className="notice">Recurring: download ECI → upload latest Excel → dashboard updates.</div></div>{error&&<div className="notice errorNotice">{error}</div>}{!master.length&&<div className="notice">First time only: load <b>For Hearing Schedule-3.xlsx</b>. It stays in this browser; after that, only ECI uploads are needed.</div>}<nav className="tabs">{['Overview','PS Wise','Hearing Centres','Pending','Validation','History','Settings'].map(t=><button className={`tab ${tab===t?'active':''}`} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>
{tab==='Overview'&&<><div className="grid">{kpis.map(([l,v,i,m])=><div className="card" key={l}><div className="cardTop"><div className="cardIcon">{i}</div><div><div className="label">{l}</div><div className="value">{fmt(Number(v))}</div><div className="meta">{m}</div></div></div></div>)}</div><div className="section"><h2>Notice status — ANOMALY and NO MAPPING shown separately</h2><div className="split">{([['ANOMALY','anGen','anPend','anDel','anPdel'],['NO MAPPING','nmGen','nmPend','nmDel','nmPdel'],['ECI TOTAL','gen','pgen','del','pdel']] as Array<[string,keyof Cat,keyof Cat,keyof Cat,keyof Cat]>).map(x=><div className={`mini ${x[0]==='ANOMALY'?'anomalyMini':x[0]==='NO MAPPING'?'mappingMini':'totalMini'}`} key={x[0]}><h3>{x[0]}</h3>{[['Generated',x[1]],['Pending Gen',x[2]],['Delivered',x[3]],['Pending Del',x[4]]].map(([l,k])=><div className="metricrow" key={l}><span>{l}</span><b>{fmt(cats(k as keyof Cat))}</b></div>)}</div>)}</div></div><div className="secondary">{secondary.map(([l,v])=><div className="secondaryItem" key={l}><span>{l}</span><b>{fmt(Number(v))}</b></div>)}</div><div className="section"><div className="sectionHead"><div><h2>PS-Wise Status — Separate ANOMALY / NO MAPPING Notices</h2><div className="hint">Live operational view · click any column heading to sort</div></div><button className="resetSort" onClick={()=>setPsSort({key:'ps',dir:'asc'})}>↻ Reset</button></div><div className="filters"><input placeholder="Search PS / BLO / locality / area..." value={q} onChange={e=>setQ(e.target.value)}/><select value={centreFilter} onChange={e=>setCentreFilter(e.target.value)}><option>All Centres</option>{centres.map(c=><option key={c}>{c}</option>)}</select><button className="resetSort exportBtn" onClick={exportCsv}>⇩ Export</button></div>{table(filtered)}</div></>}
{tab==='PS Wise'&&<div className="section"><div className="sectionHead"><div><h2>PS-Wise Status — Separate ANOMALY / NO MAPPING Notices</h2><div className="hint">Click any column heading to sort. ↑ ascending · ↓ descending</div></div><button className="resetSort" onClick={()=>setPsSort({key:'ps',dir:'asc'})}>↻ Reset sort</button></div><div className="filters"><input placeholder="Search PS / BLO / locality / area..." value={q} onChange={e=>setQ(e.target.value)}/><select value={centreFilter} onChange={e=>setCentreFilter(e.target.value)}><option>All Centres</option>{centres.map(c=><option key={c}>{c}</option>)}</select><button className="resetSort exportBtn" onClick={exportCsv}>⇩ Export</button></div>{table(filtered)}</div>}
{tab==='Hearing Centres'&&<div className="section"><div className="sectionHead"><div><h2>Hearing Centre Reconciliation — Separate ANOMALY / NO MAPPING</h2><div className="hint">Click any column heading to sort. ↑ ascending · ↓ descending</div></div><button className="resetSort" onClick={()=>setCentreSort({key:'centre',dir:'asc'})}>↻ Reset sort</button></div><div className="tablewrap"><table><thead><tr>{th('Hearing Centre','centre',centreSort,setCentreSort)}{th('Officer','officer',centreSort,setCentreSort)}{th('Contact','contact',centreSort,setCentreSort)}{th('PS','ps',centreSort,setCentreSort)}<th colSpan={2}>GENERATED</th><th colSpan={2}>PENDING GENERATION</th><th colSpan={2}>DELIVERED</th><th colSpan={2}>PENDING DELIVERY</th>{th('DEO >5','deo5',centreSort,setCentreSort)}</tr><tr>{['anGen','nmGen','anPend','nmPend','anDel','nmDel','anPdel','nmPdel'].map((k,i)=><th key={k} className="sortable" onClick={()=>toggle(setCentreSort,centreSort,k)}>{i%2?'NO MAP':'ANOM'}{arrow(centreSort,k)}</th>)}</tr></thead><tbody>{sortedCentres.map(r=><tr key={r.centre}><td>{r.centre}</td><td>{r.officer}</td><td>{r.contact}</td><td>{r.ps}</td><td className="anom">{fmt(r.anGen)}</td><td className="nomap">{fmt(r.nmGen)}</td><td className="anom">{fmt(r.anPend)}</td><td className="nomap">{fmt(r.nmPend)}</td><td className="anom">{fmt(r.anDel)}</td><td className="nomap">{fmt(r.nmDel)}</td><td className="anom">{fmt(r.anPdel)}</td><td className="nomap">{fmt(r.nmPdel)}</td><td>{fmt(r.deo5)}</td></tr>)}</tbody></table></div></div>}
{tab==='Pending'&&<div className="section"><div className="sectionHead"><div><h2>Operational Pending Report — Separate ANOMALY / NO MAPPING</h2><div className="hint">Pending generation and delivery are always shown separately</div></div><button className="resetSort" onClick={()=>setPsSort({key:'ps',dir:'asc'})}>↻ Reset sort</button></div><div className="filters"><input placeholder="Search PS / BLO / locality / area..." value={q} onChange={e=>setQ(e.target.value)}/><select value={centreFilter} onChange={e=>setCentreFilter(e.target.value)}><option>All Centres</option>{centres.map(c=><option key={c}>{c}</option>)}</select><button className="resetSort exportBtn" onClick={exportCsv}>⇩ Export</button></div>{table(filtered.filter(r=>r.cat.anPend+r.cat.nmPend+r.cat.anPdel+r.cat.nmPdel+n(r['Hearing Date Lapsed'])+n(r['Reschedule Date Lapsed'])+n(r['DEO-Status Total Pending'])>0))}</div>}
{tab==='Validation'&&<div className="section"><div className="sectionHead"><div><h2>Data Validation & Reconciliation</h2><div className="hint">All reconciliation checks remain visible; source data is never silently altered.</div></div><button className="resetSort" onClick={()=>setValidationSort({key:'label',dir:'asc'})}>↻ Reset sort</button></div><div className="validationTable"><table><thead><tr>{th('Check','label',validationSort,setValidationSort)}{th('Actual','actual',validationSort,setValidationSort)}{th('Expected','expected',validationSort,setValidationSort)}{th('Result','result',validationSort,setValidationSort)}</tr></thead><tbody>{sortedValidation.map(([label,actual,expected,ok])=><tr key={label}><td>{label}</td><td>{fmt(actual)}</td><td>{fmt(expected)}</td><td><span className={`statusBadge ${ok?'clear':'critical'}`}>{ok?'PASS':'CHECK'}</span></td></tr>)}</tbody></table></div><div className="small">Category notices are never silently forced to match master totals. ECI aggregates are split using the confirmed NO MAPPING first → ANOMALY rule, and each split is reconciled back to its ECI source field.</div></div>}
{tab==='History'&&<div className="section infoPanel"><h2>Upload History</h2><div className="historyRow"><span>Latest ECI upload</span><b>{updated||'No upload recorded'}</b></div><div className="historyRow"><span>Master data</span><b>{master.length===430?'Loaded · 430 PS':'Not loaded'}</b></div><div className="historyRow"><span>Current ECI data</span><b>{eci.length===430?'Loaded · 430 PS':'Not loaded'}</b></div></div>}
{tab==='Settings'&&<div className="section infoPanel"><h2>Dashboard Settings</h2><div className="historyRow"><span>Theme</span><b>Dark / Operations</b></div><div className="historyRow"><span>Category allocation</span><b>NO MAPPING first → ANOMALY</b></div><div className="historyRow"><span>Operational scope</span><b>430 Polling Stations · NCT of Delhi</b></div></div>}
<div className="footer">Election Commission of India — SIR Hearing & Notice Monitoring &nbsp;|&nbsp; NCT of Delhi</div></div></main>}
