'use client';
import { useEffect } from 'react';
import './generated-notices.module.css';
import Dashboard from './EnhancedDashboard';
import ReportExport from './ReportExport';

function DashboardEnhancer(){
  useEffect(()=>{
    const sortState=new WeakMap<HTMLTableElement,{index:number,asc:boolean}>();
    const parse=(v:string)=>{const x=v.replace(/,/g,'').replace(/%/g,'').trim();return x!==''&&Number.isFinite(Number(x))?Number(x):v.toLowerCase()};
    const normalize=(v:string)=>v.replace(/\s+/g,' ').trim().toUpperCase();
    const filterPSWise=(table:HTMLTableElement,value:string)=>{Array.from(table.tBodies[0]?.rows||[]).forEach(row=>{const status=row.cells[row.cells.length-1]?.dataset.categoryStatus||'';row.style.display=value==='All Status'||status.split(' | ').includes(value)?'':'none';});};
    const enhancePSWiseStatus=(table:HTMLTableElement)=>{const headers=Array.from(table.querySelectorAll('thead tr:first-child th')) as HTMLTableCellElement[];const labels=headers.map(h=>normalize(h.innerText||''));if(!labels.includes('ANOM PENDING GEN')||!labels.includes('NO MAP PENDING GEN'))return;const statusHeader=headers[labels.indexOf('STATUS')];if(!statusHeader)return;let select=statusHeader.querySelector('select') as HTMLSelectElement|null;if(!select){statusHeader.dataset.statusDropdownEnhanced='1';statusHeader.classList.remove('sortable');statusHeader.removeAttribute('title');select=document.createElement('select');select.setAttribute('aria-label','PS Wise Category Status');select.style.cssText='min-width:220px;font-size:11px;font-weight:700;padding:5px 8px;border-radius:6px';const options=['All Status','ANOMALY · PENDING GENERATION','NO MAPPING · PENDING GENERATION','ANOMALY · GENERATED','NO MAPPING · GENERATED','ANOMALY · CLEAR','NO MAPPING · CLEAR'];options.forEach(x=>{const o=document.createElement('option');o.value=x;o.textContent=x;select!.appendChild(o)});statusHeader.replaceChildren(select);select.addEventListener('click',e=>e.stopPropagation());select.addEventListener('change',()=>filterPSWise(table,select!.value));}Array.from(table.tBodies[0]?.rows||[]).forEach(row=>{const cells=row.cells;const anPend=Number((cells[6]?.innerText||'0').replace(/,/g,''));const nmPend=Number((cells[8]?.innerText||'0').replace(/,/g,''));const anGen=Number((cells[5]?.innerText||'0').replace(/,/g,''));const nmGen=Number((cells[7]?.innerText||'0').replace(/,/g,''));const cell=cells[cells.length-1];if(!cell)return;const statuses:string[]=[];if(anPend>0)statuses.push('ANOMALY · PENDING GENERATION');else if(anGen>0)statuses.push('ANOMALY · GENERATED');else statuses.push('ANOMALY · CLEAR');if(nmPend>0)statuses.push('NO MAPPING · PENDING GENERATION');else if(nmGen>0)statuses.push('NO MAPPING · GENERATED');else statuses.push('NO MAPPING · CLEAR');const value=statuses.join(' | ');cell.dataset.categoryStatus=value;cell.textContent=value;});select=statusHeader.querySelector('select') as HTMLSelectElement|null;if(select)filterPSWise(table,select.value||'All');};
    const enhanceGenerated=(table:HTMLTableElement)=>{const headers=Array.from(table.querySelectorAll('thead tr:first-child th')) as HTMLTableCellElement[];const labels=headers.map(h=>normalize(h.innerText||''));if(!labels.includes('ANOMALY')||!labels.includes('NO MAPPING'))return;Array.from(table.tBodies[0]?.rows||[]).forEach(row=>{const cells=row.cells;const anGen=Number((cells[5]?.innerText||'0').replace(/,/g,''));const anDel=Number((cells[6]?.innerText||'0').replace(/,/g,''));const anPdel=Number((cells[7]?.innerText||'0').replace(/,/g,''));const nmGen=Number((cells[9]?.innerText||'0').replace(/,/g,''));const nmDel=Number((cells[10]?.innerText||'0').replace(/,/g,''));const nmPdel=Number((cells[11]?.innerText||'0').replace(/,/g,''));const generated=anGen+nmGen;const delivered=anDel+nmDel;const pendingDelivery=anPdel+nmPdel;const cell=cells[cells.length-2];if(!cell||generated<=0)return;const type=anGen>0&&nmGen>0?'MIXED':anGen>0?'ANOMALY':'NO MAPPING';let base='CHECK';if(delivered>=generated)base='FULLY DELIVERED';else if(delivered>0&&pendingDelivery>0)base='PARTIAL DELIVERY';else if(delivered===0&&pendingDelivery>0)base='NOT DELIVERED';const next=`${base} · ${type}`;if(cell.dataset.generatedStatus!==next){cell.dataset.generatedStatus=next;const badge=document.createElement('span');badge.className='deliveryBadge';badge.textContent=next;cell.replaceChildren(badge);}});};
    const enhanceGeneratedFilter=()=>{const active=document.querySelector('.tab.active')?.textContent?.trim()||'';if(active!=='Generated Notices')return;const selects=Array.from(document.querySelectorAll('select')) as HTMLSelectElement[];const status=selects.find(x=>x.getAttribute('aria-label')==='Status')||selects.find(x=>Array.from(x.options).some(o=>normalize(o.textContent||'').includes('FULLY DELIVERED')));if(!status)return;const valid=['All','NO MAPPING · FULLY DELIVERED','NO MAPPING · PARTIAL DELIVERY','NO MAPPING · NOT DELIVERED','ANOMALY · FULLY DELIVERED','ANOMALY · PARTIAL DELIVERY','ANOMALY · NOT DELIVERED','MIXED · FULLY DELIVERED','MIXED · PARTIAL DELIVERY','MIXED · NOT DELIVERED'];if(status.dataset.generatedFilterEnhanced!=='1'){status.dataset.generatedFilterEnhanced='1';const current=status.value;status.replaceChildren(...valid.map(x=>{const o=document.createElement('option');o.value=x;o.textContent=x==='All'?'All Status':x;return o}));status.value=valid.includes(current)?current:'All';if(status.value!==current)status.dispatchEvent(new Event('change',{bubbles:true}));}};
    const enhanceOverviewAnomalyTotal=()=>{const active=document.querySelector('.tab.active')?.textContent?.trim()||'';if(active!=='Overview')return;let masterTotal=0;try{const raw=localStorage.getItem('eci-master');const rows=raw?JSON.parse(raw):[];if(Array.isArray(rows))masterTotal=rows.reduce((x,r)=>x+Number(r?.anomaly||0),0);}catch{}if(!masterTotal)return;document.querySelectorAll('[data-anomaly-master-total="1"]').forEach(el=>el.remove());const heads=Array.from(document.querySelectorAll('body *')).filter(el=>el.children.length===0&&(el.textContent||'').trim().toUpperCase()==='ANOMALY');const heading=heads.find(el=>{let p=el.parentElement;for(let i=0;i<6&&p;i++,p=p.parentElement){const t=p.textContent||'';if(t.includes('Generated')&&t.includes('Pending Gen')&&t.includes('Delivered')&&t.includes('Pending Del'))return true;}return false;});if(!heading)return;let card=heading.parentElement as HTMLElement|null;while(card){const t=card.textContent||'';if(t.includes('Generated')&&t.includes('Pending Gen')&&t.includes('Delivered')&&t.includes('Pending Del'))break;card=card.parentElement;}if(!card)return;const row=document.createElement('div');row.setAttribute('data-anomaly-master-total','1');row.style.cssText='display:flex;justify-content:space-between;align-items:center;padding:6px 0;border-bottom:1px solid rgba(255,255,255,.08);';row.innerHTML='<span style="font-weight:700">Total Anomaly</span><strong style="font-size:15px">'+masterTotal.toLocaleString('en-IN')+'</strong>';card.insertBefore(row,card.firstElementChild?.nextElementSibling||card.firstElementChild);};
    const enhanceNoMappingPendingReport=()=>{
      const active=document.querySelector('.tab.active')?.textContent?.trim()||'';
      if(active!=='Reports')return;
      const existing=document.querySelector('[data-no-mapping-pending-report="1"]');
      if(existing)return;
      let master:any[]=[];let eci:any[]=[];
      try{master=JSON.parse(localStorage.getItem('eci-master')||'[]');eci=JSON.parse(localStorage.getItem('eci-current')||'[]');}catch{return;}
      if(!Array.isArray(master)||!master.length||!Array.isArray(eci)||!eci.length)return;
      const eMap=new Map<number,any>(eci.map(r=>[Number(r?.ps),r]));
      const person=(value:any)=>{const v=String(value??'').replace(/\s+/g,' ').trim();const m=v.match(/^(.*?)\s*\(\s*(\d{10})\s*\)\s*$/);return m?{name:m[1].trim(),phone:m[2]}:{name:v,phone:''};};
      const rows=master.map(m=>{const ps=Number(m?.ps);const e=eMap.get(ps);if(!e)return null;const mapping=Math.max(Number(m?.mapping)||0,0);const generated=Math.max(Number(e?.['Notice Generated'])||0,0);const eciPending=Math.max(Number(e?.['Pending for Notice Generation'])||0,0);const nmGenerated=Math.min(generated,mapping);const pending=Math.min(eciPending,Math.max(mapping-nmGenerated,0));if(pending<=0)return null;const blo=person(m?.blo);return{ps,oldPs:m?.oldPs??null,bloName:blo.name,bloPhone:blo.phone,officer:String(m?.officer??'').replace(/\s+/g,' ').trim(),centre:String(m?.hearingCentre??'').replace(/\s+/g,' ').trim(),mapping,generated:nmGenerated,pending};}).filter(Boolean).sort((a:any,b:any)=>b.pending-a.pending||a.ps-b.ps) as any[];
      const host=document.querySelector('.app main.wrap');if(!host)return;
      const section=document.createElement('div');section.setAttribute('data-no-mapping-pending-report','1');section.className='section';section.style.marginTop='14px';
      const totalPending=rows.reduce((a,r)=>a+r.pending,0);
      const head=document.createElement('div');head.className='sectionHead';head.innerHTML='<div><h2 style="margin-bottom:3px">NO MAPPING NOTICE GENERATION PENDING — PS WISE</h2><div class="hint">Only PS with pending No Mapping notice generation are shown · Sorted by pending quantity</div></div><strong style="font-size:18px;color:#ff8a8a">'+totalPending.toLocaleString('en-IN')+' Pending</strong>';section.appendChild(head);
      const wrap=document.createElement('div');wrap.className='tablewrap';
      const table=document.createElement('table');table.innerHTML='<thead><tr><th>S. No.</th><th>PS No.</th><th>Old PS</th><th>BLO Name</th><th>BLO Mobile No.</th><th>Officer Name</th><th>Hearing Centre</th><th>Total No Mapping</th><th>No Mapping Generated</th><th>Pending Generation</th></tr></thead><tbody></tbody>';
      const tbody=table.tBodies[0];rows.forEach((r,i)=>{const tr=document.createElement('tr');const vals=[String(i+1),String(r.ps),r.oldPs==null?'—':String(r.oldPs),r.bloName||'—',r.bloPhone||'—',r.officer||'—',r.centre||'—',r.mapping.toLocaleString('en-IN'),r.generated.toLocaleString('en-IN'),r.pending.toLocaleString('en-IN')];vals.forEach((v,j)=>{const td=document.createElement('td');td.textContent=v;if(j===9){td.style.fontWeight='800';td.style.color='#ff8a8a';}if(j===0||j===1||j===2||j>=7)td.style.textAlign='center';tr.appendChild(td);});tbody.appendChild(tr);});
      if(!rows.length){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=10;td.textContent='No No-Mapping notice generation is currently pending.';td.style.textAlign='center';tr.appendChild(td);tbody.appendChild(tr);}
      wrap.appendChild(table);section.appendChild(wrap);host.appendChild(section);
    };
    const attach=(table:HTMLTableElement)=>{enhancePSWiseStatus(table);enhanceGenerated(table);const headers=Array.from(table.querySelectorAll('thead tr:first-child th')) as HTMLTableCellElement[];const active=document.querySelector('.tab.active')?.textContent?.trim()||'';headers.forEach((h,index)=>{if(h.dataset.enhancedSort==='1'||h.dataset.statusDropdownEnhanced==='1'||h.getAttribute('colspan'))return;const label=(h.innerText||'').replace(/\s[↑↓]$/,'').trim();if(normalize(label)==='STATUS')return;h.dataset.enhancedSort='1';h.classList.add('sortable');h.title='Click to sort';h.addEventListener('click',ev=>{ev.stopPropagation();let cellIndex=index;const currentLabel=(h.innerText||'').replace(/\s[↑↓]$/,'').trim();if(active==='Generated Notices'){const map:Record<string,number>={PS:0,'Old PS':1,BLO:2,Officer:3,'Hearing Location':4,'Delivery %':16,Hearings:17};if(!(currentLabel in map))return;cellIndex=map[currentLabel];}const old=sortState.get(table);const asc=old?.index===cellIndex?!old.asc:true;sortState.set(table,{index:cellIndex,asc});const body=table.tBodies[0];if(!body)return;const rows=Array.from(body.rows).filter(r=>r.style.display!=='none');const hidden=Array.from(body.rows).filter(r=>r.style.display==='none');rows.sort((a,b)=>{const aa=parse(a.cells[cellIndex]?.innerText||'');const bb=parse(b.cells[cellIndex]?.innerText||'');const c=typeof aa==='number'&&typeof bb==='number'?aa-bb:String(aa).localeCompare(String(bb),undefined,{numeric:true,sensitivity:'base'});return asc?c:-c;});[...rows,...hidden].forEach(r=>body.appendChild(r));headers.forEach(x=>{if(!x.querySelector('select'))x.textContent=x.textContent?.replace(/\s[↑↓]$/,'')||''});h.textContent=(h.textContent||'').replace(/\s[↑↓]$/,'')+(asc?' ↑':' ↓');});});};
    let decorating=false;const decorate=()=>{if(decorating)return;decorating=true;try{document.querySelectorAll('table').forEach(t=>attach(t as HTMLTableElement));enhanceGeneratedFilter();enhanceOverviewAnomalyTotal();enhanceNoMappingPendingReport();}finally{decorating=false}};let scheduled=false;const scheduleDecorate=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;decorate()});};const observer=new MutationObserver(scheduleDecorate);observer.observe(document.body,{subtree:true,childList:true});scheduleDecorate();return()=>observer.disconnect();
  },[]);
  return null;
}

export default function Page(){return <><Dashboard/><ReportExport/><DashboardEnhancer/></>}
