'use client';
import { useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';

type Master = {ps:number;oldPs?:number|null;anomaly:number;mapping:number;grandTotal:number;blo?:string|null;supervisor?:string|null;officer?:string|null;officerNew?:string|null;hearingCentre?:string|null;address?:string|null;locality?:string|null;pollingArea?:string|null;voters:number};
type Eci = Record<string, any> & {ps:number};
const MAP=[
 ['GCSSS, SEC-3 DWARKA(P)',1,50,'SH. PARVEEN KUMAR','9953601073'],['GCSSS, SEC-3 DWARKA(P)',55,60,'SH. PARVEEN KUMAR','9953601073'],['GCSSS, SEC-3 DWARKA(P)',78,79,'SH. PARVEEN KUMAR','9953601073'],['GCSSS, SEC-3 DWARKA(P)',91,96,'SH. PARVEEN KUMAR','9953601073'],
 ['GCSSS, SEC-3 DWARKA(S)',51,54,'SMT. SHASHI BALA','9953312984'],['GCSSS, SEC-3 DWARKA(S)',61,77,'SMT. SHASHI BALA','9953312984'],['GCSSS, SEC-3 DWARKA(S)',80,90,'SMT. SHASHI BALA','9953312984'],['GCSSS, SEC-3 DWARKA(S)',97,109,'SMT. SHASHI BALA','9953312984'],['GCSSS, SEC-3 DWARKA(S)',135,145,'SMT. SHASHI BALA','9953312984'],
 ['GCSSC SEC-22 DWARKA(R)',110,134,'SH. RAKESH KUMAR','7011971522'],['GCSSC SEC-22 DWARKA(R)',331,341,'SH. RAKESH KUMAR','7011971522'],['GCSSC SEC-22 DWARKA(R)',343,344,'SH. RAKESH KUMAR','7011971522'],['GCSSC SEC-22 DWARKA(R)',347,349,'SH. RAKESH KUMAR','7011971522'],
 ['VREC MATIALA',146,234,'SMT. PARUL GUPTA','9667881989'],['VREC MATIALA',276,288,'SMT. PARUL GUPTA','9667881989'],
 ['MCD BOYS PRIMARY SCHOOL, QUTUB VIHAR',235,275,'SH. SUBHASHISH','9868252144'],['MCD BOYS PRIMARY SCHOOL, QUTUB VIHAR',289,330,'SH. SUBHASHISH','9868252144'],
 ['GCSSS SEC 22 DWARKA(V)',342,342,'SH. VIRENDER','9868252144'],['GCSSS SEC 22 DWARKA(V)',345,346,'SH. VIRENDER','9868252144'],['GCSSS SEC 22 DWARKA(V)',350,374,'SH. VIRENDER','9868252144'],
 ['GCSSS GHUMANHERA',375,430,'SH. VIRENDER','9868252144']
] as const;
function centre(ps:number){const x=MAP.find(m=>ps>=m[1]&&ps<=m[2]);return x?{centre:x[0],officer:x[3],contact:x[4]}:null}
const n=(v:any)=>{const x=Number(v);return Number.isFinite(x)?x:0}; const norm=(v:any)=>String(v??'').trim();
function parseRows(rows:any[][]):Eci[]{const heads=rows[0].map((x:any)=>norm(x)); const ix=(name:string)=>heads.indexOf(name); return rows.slice(1).filter(r=>r.some((x:any)=>x!==''&&x!=null)).map(r=>{const o:any={}; heads.forEach((h:string,i:number)=>{if(h)o[h]=r[i]}); o.ps=Math.trunc(n(r[ix('POLLING STATION')])); return o}).filter(x=>x.ps>=1&&x.ps<=430)}
function category(e:Eci,m:Master){const gen=n(e['Notice Generated']),del=n(e['Notice Delivered']); const nmGen=Math.min(gen,m.mapping); const anGen=gen-nmGen; const nmDel=Math.min(del,nmGen); const anDel=del-nmDel; const nmPend=Math.max(m.mapping-nmGen,0); const anPend=Math.max(m.anomaly-anGen,0); return {nmGen,anGen,nmDel,anDel,nmPend,anPend,nmPdel:Math.max(nmGen-nmDel,0),anPdel:Math.max(anGen-anDel,0),gen,del,pgen:n(e['Pending for Notice Generation']),pdel:n(e['Notice Pending Delivery']),recon:(nmPend+anPend)-n(e['Pending for Notice Generation'])};}
export default function Dashboard(){
 const [master,setMaster]=useState<Master[]>([]); const [eci,setEci]=useState<Eci[]>([]); const [tab,setTab]=useState('Overview'); const [q,setQ]=useState(''); const [centreFilter,setCentreFilter]=useState('All'); const [updated,setUpdated]=useState(''); const [error,setError]=useState('');
 useEffect(()=>{try{const m=localStorage.getItem('eci-master');if(m)setMaster(JSON.parse(m));const t=localStorage.getItem('eci-updated');if(t)setUpdated(t);const x=localStorage.getItem('eci-current');if(x)setEci(JSON.parse(x))}catch{}},[]);
 const upload=async(file:File,type:'eci'|'master')=>{setError('');try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const ws=type==='eci'?(wb.Sheets['sirNoticeGenerate']||wb.Sheets[wb.SheetNames[0]]):(wb.Sheets['Rough Data']||wb.Sheets[wb.SheetNames[0]]);const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''}) as any[][];if(type==='eci'){const parsed=parseRows(rows);if(parsed.length!==430)throw new Error(`ECI file has ${parsed.length} valid PS rows; expected 430.`);const dup=parsed.length-new Set(parsed.map(x=>x.ps)).size;if(dup)throw new Error(`ECI file has ${dup} duplicate PS key(s).`);setEci(parsed);const now=new Date().toLocaleString('en-IN',{hour12:false});setUpdated(now);localStorage.setItem('eci-updated',now);localStorage.setItem('eci-current',JSON.stringify(parsed))}else{const heads=rows[1].map((x:any)=>norm(x));const idx=(name:string)=>heads.indexOf(name);const parsed=rows.slice(2).filter(r=>r[idx('New P.S. No.')]!==''&&r[idx('New P.S. No.')]!=null).map(r=>({ps:Math.trunc(n(r[idx('New P.S. No.')])),oldPs:r[idx('Old P.S. No.')]=== ''?null:n(r[idx('Old P.S. No.')] ),anomaly:n(r[idx('Total Anamoly/Discripancy')]),mapping:n(r[idx('Total No Mapping')]),grandTotal:n(r[idx('Grand Total')]),blo:r[idx('All BLO Name')],supervisor:r[idx('Supervisor Name')],officer:r[idx('Officer Name (NEW)')],officerNew:r[idx('Officer Name (NEW)')],hearingCentre:r[idx('Hearing Centre')],address:r[idx('Address of P.S.')],locality:r[idx('LOCALITY')],pollingArea:r[idx('POLLING AREA')],voters:n(r[idx('Total Voters')])}));if(parsed.length!==430)throw new Error(`Master file has ${parsed.length} PS rows; expected 430.`);setMaster(parsed);localStorage.setItem('eci-master',JSON.stringify(parsed))}}catch(e:any){setError(e.message||'Could not read workbook')}};
 const joined=useMemo(()=>{const mm=new Map(master.map(m=>[m.ps,m]));return eci.map(e=>{const m=mm.get(e.ps)||{ps:e.ps,anomaly:0,mapping:0,grandTotal:0,voters:0};return {...e,m,cat:category(e,m),map:centre(e.ps)}})},[eci,master]);
 const filtered=joined.filter(r=>(centreFilter==='All'||r.map?.centre===centreFilter)&&(q===''||String(r.ps).includes(q)||norm(r.m.blo).toLowerCase().includes(q.toLowerCase())||norm(r.m.locality).toLowerCase().includes(q.toLowerCase())));
 const sum=(k:string)=>joined.reduce((a,r)=>a+n(r[k]),0); const cats=(k:string)=>joined.reduce((a,r)=>a+n(r.cat[k]),0); const centres=[...new Set(MAP.map(x=>x[0]))];
 const status=(r:any)=>n(r['DEO-Status Pending GT 5 Days'])>0||n(r['Hearing Date Lapsed'])>0||n(r['Reschedule Date Lapsed'])>0?'CRITICAL':n(r['Pending for Notice Generation'])>0||n(r['Notice Pending Delivery'])>0||n(r['DEO-Status Total Pending'])>0?'PENDING':'CLEAR';
 const kpis=[['Total PS',430],['Notice Generated',sum('Notice Generated')],['Pending Generation',sum('Pending for Notice Generation')],['Notice Delivered',sum('Notice Delivered')],['Pending Delivery',sum('Notice Pending Delivery')],['Hearings Held',sum('Hearings Held')],['Hearing Lapsed',sum('Hearing Date Lapsed')],['Reschedule Lapsed',sum('Reschedule Date Lapsed')],['DEO Pending',sum('DEO-Status Total Pending')],['DEO >5 Days',sum('DEO-Status Pending GT 5 Days')],['DEO Verified',sum('DEO-Status Verified')],['DEO Not Verified',sum('DEO-Status Not Verified')]];
 return <main className="app"><header className="topbar"><div><div className="brand">ECI HEARING & NOTICE MONITORING</div><div className="sub">NCT OF DELHI · 430 POLLING STATIONS · LIVE ECI UPLOAD DASHBOARD</div></div><div className="updated">{updated?`Last upload: ${updated}`:'No ECI upload yet'}</div></header><div className="wrap"><div className="toolbar"><div className="upload"><label>Upload ECI Excel<input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'eci')}/></label><label>Load Master (one-time)<input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'master')}/></label></div><div className="notice">Recurring: download ECI → upload latest Excel → dashboard updates.</div></div>{error&&<div className="notice" style={{background:'#fff1f0',borderColor:'#fecdca',marginBottom:15}}>{error}</div>}{!master.length&&<div className="notice" style={{marginBottom:15}}>First time only: load <b>For Hearing Schedule-3.xlsx</b>. It stays in this browser; after that, only ECI uploads are needed.</div>}<div className="tabs">{['Overview','PS Wise','Hearing Centres','Pending','Validation'].map(t=><button className={`tab ${tab===t?'active':''}`} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>
 {tab==='Overview'&&<><div className="grid">{kpis.map(([l,v])=><div className="card" key={String(l)}><div className="label">{l}</div><div className="value">{Number(v).toLocaleString('en-IN')}</div></div>)}</div><div className="section"><h2>Notice status — separate Anomaly / No Mapping view</h2><div className="split">{[['ANOMALY','anGen','anPend','anDel','anPdel'],['NO MAPPING','nmGen','nmPend','nmDel','nmPdel'],['ECI TOTAL','gen','pgen','del','pdel']].map(x=><div className="mini" key={x[0]}><h3>{x[0]}</h3><div className="metricrow"><span>Generated</span><b>{cats(x[1]).toLocaleString('en-IN')}</b></div><div className="metricrow"><span>Pending Generation</span><b>{cats(x[2]).toLocaleString('en-IN')}</b></div><div className="metricrow"><span>Delivered</span><b>{cats(x[3]).toLocaleString('en-IN')}</b></div><div className="metricrow"><span>Pending Delivery</span><b>{cats(x[4]).toLocaleString('en-IN')}</b></div></div>)}</div><div className="small" style={{padding:'0 14px 14px'}}>The category split is derived from master category counts and ECI totals. Any mismatch is surfaced in Validation rather than hidden.</div></div></>}
 {tab==='PS Wise'&&<div className="section"><h2>PS-wise consolidated status</h2><div className="filters"><input placeholder="Search PS / BLO / locality" value={q} onChange={e=>setQ(e.target.value)}/><select value={centreFilter} onChange={e=>setCentreFilter(e.target.value)}><option>All</option>{centres.map(c=><option key={c}>{c}</option>)}</select></div><div className="tablewrap"><table className="table"><thead><tr><th>PS</th><th>Old PS</th><th>BLO</th><th>Locality</th><th>Centre</th><th>Anomaly</th><th>No Mapping</th><th>Generated</th><th>Pending Gen</th><th>Delivered</th><th>Pending Delivery</th><th>Hearings</th><th>DEO &gt;5</th><th>Status</th></tr></thead><tbody>{filtered.map(r=><tr key={r.ps}><td><b>{r.ps}</b></td><td>{r.m.oldPs??''}</td><td>{norm(r.m.blo).replace(/\n/g,' ')}</td><td>{r.m.locality||''}</td><td>{r.map?.centre||r.m.hearingCentre||''}</td><td>{r.m.anomaly}</td><td>{r.m.mapping}</td><td>{n(r['Notice Generated'])}</td><td>{n(r['Pending for Notice Generation'])}</td><td>{n(r['Notice Delivered'])}</td><td>{n(r['Notice Pending Delivery'])}</td><td>{n(r['Hearings Held'])}</td><td>{n(r['DEO-Status Pending GT 5 Days'])}</td><td className={`status ${status(r)==='CRITICAL'?'critical':status(r)==='PENDING'?'pending':'clear'}`}>{status(r)}</td></tr>)}</tbody></table></div></div>}
 {tab==='Hearing Centres'&&<div className="section"><h2>Hearing-centre reconciliation</h2><div className="tablewrap"><table className="table"><thead><tr><th>Hearing Centre</th><th>Officer</th><th>Contact</th><th>Allocated</th><th>Actual</th><th>Generated</th><th>Pending Gen</th><th>Delivered</th><th>Pending Delivery</th><th>Hearings</th><th>DEO &gt;5</th></tr></thead><tbody>{centres.map(c=>{const rr=joined.filter(r=>r.map?.centre===c);const meta=MAP.find(x=>x[0]===c)!;return <tr key={c}><td>{c}</td><td>{meta[3]}</td><td>{meta[4]}</td><td>{rr.length}</td><td>{rr.length}</td><td>{rr.reduce((a,r)=>a+n(r['Notice Generated']),0)}</td><td>{rr.reduce((a,r)=>a+n(r['Pending for Notice Generation']),0)}</td><td>{rr.reduce((a,r)=>a+n(r['Notice Delivered']),0)}</td><td>{rr.reduce((a,r)=>a+n(r['Notice Pending Delivery']),0)}</td><td>{rr.reduce((a,r)=>a+n(r['Hearings Held']),0)}</td><td>{rr.reduce((a,r)=>a+n(r['DEO-Status Pending GT 5 Days']),0)}</td></tr>})}</tbody></table></div></div>}
 {tab==='Pending'&&<div className="section"><h2>Operational pending report</h2><div className="tablewrap"><table className="table"><thead><tr><th>PS</th><th>BLO</th><th>Officer</th><th>Centre</th><th>Pending Gen</th><th>Pending Delivery</th><th>Hearing Lapsed</th><th>Reschedule Lapsed</th><th>DEO Pending</th><th>DEO &gt;5</th><th>Hearings</th><th>Priority</th></tr></thead><tbody>{joined.filter(r=>status(r)!=='CLEAR').sort((a,b)=>n(b['DEO-Status Pending GT 5 Days'])-n(a['DEO-Status Pending GT 5 Days'])).map(r=><tr key={r.ps}><td><b>{r.ps}</b></td><td>{norm(r.m.blo).replace(/\n/g,' ')}</td><td>{r.map?.officer||''}</td><td>{r.map?.centre||''}</td><td>{n(r['Pending for Notice Generation'])}</td><td>{n(r['Notice Pending Delivery'])}</td><td>{n(r['Hearing Date Lapsed'])}</td><td>{n(r['Reschedule Date Lapsed'])}</td><td>{n(r['DEO-Status Total Pending'])}</td><td>{n(r['DEO-Status Pending GT 5 Days'])}</td><td>{n(r['Hearings Held'])}</td><td className={`status ${status(r)==='CRITICAL'?'critical':'pending'}`}>{status(r)}</td></tr>)}</tbody></table></div></div>}
 {tab==='Validation'&&<div className="section"><h2>Data validation & reconciliation</h2><div className="validation">{[['ECI PS count',eci.length,430],['Master PS count',master.length,430],['Unique ECI PS',new Set(eci.map(r=>r.ps)).size,430],['Centre allocation',centres.reduce((a,c)=>a+joined.filter(r=>r.map?.centre===c).length,0),430]].map(([l,v,t])=><div className={`check ${v===t?'pass':'err'}`} key={String(l)}><b>{l}</b><div style={{fontSize:22,fontWeight:800,marginTop:6}}>{v} / {t}</div><div className="small">{v===t?'PASS':'ERROR'}</div></div>)}<div className="check warn"><b>Category reconciliation differences</b><div style={{fontSize:22,fontWeight:800,marginTop:6}}>{joined.filter(r=>r.cat.recon!==0).length}</div><div className="small">PS where derived category pending does not exactly equal ECI pending generation.</div></div></div></div>}
 <div className="footer">Processing is performed in the browser. Master data is stored locally in this browser; the public repository does not contain the master workbook.</div></div></main>}
